#!/usr/bin/env python3
"""
Generate stickers manifest for EmoGdream
Scans public/stickers/ directory and creates a TypeScript file with all emoji data
"""

import os
from pathlib import Path
import json

CHARACTER_NAMES = {
    'nina': 'Nina',
    'nijika': 'Nijika',
    'tomori': 'Tomori',
    'momoka': 'Momoka',
    'subaru': 'Subaru',
    'hitori': 'Hitori',
    'ikuyo': 'Ikuyo',
    'soyo': 'Soyo',
    'taki': 'Taki',
    'tomo': 'Tomo',
    'rupa': 'Rupa',
    'sakiko': 'Sakiko',
    'ryo': 'Ryo',
    'uika': 'Uika',
    'nyamu': 'Nyamu',
    'mutsumi': 'Mutsumi',
    'raana': 'Raana',
    'umiri': 'Umiri',
    'gbc': 'GBC',
    'anon': 'Anon',
    'KB': 'KB',
    'mana': 'Mana'
}

def scan_stickers():
    """Scan public/stickers directory and return emoji data"""
    stickers_dir = Path('public/stickers')
    emojis = []

    for char_dir in sorted(stickers_dir.iterdir()):
        if not char_dir.is_dir() or char_dir.name.startswith('.'):
            continue

        character = char_dir.name
        for file_path in sorted(char_dir.iterdir()):
            if file_path.suffix.lower() not in ['.png', '.gif', '.webp']:
                continue

            # Extract emotion from filename
            # Format: character_emotion.ext
            filename = file_path.name
            ext = file_path.suffix.lower().lstrip('.')
            emotion = filename.replace(f'{character}_', '').replace(f'.{ext}', '')

            # Clean up emotion name
            emotion = emotion.replace('？', '').replace('·', '').replace('！', '').replace('!', '').replace('?', '').strip()
            if not emotion:
                emotion = 'unknown'

            emojis.append({
                'id': f'{character}_{emotion}_{ext}',
                'name': filename,
                'emotion': emotion,
                'format': ext,
                'character': character,
                'path': f'/stickers/{character}/{filename}'  # Use /stickers/ path (Vite serves public at root)
            })

    return emojis

def generate_ts_file(emojis):
    """Generate TypeScript file with emoji data"""
    ts_content = """// Auto-generated stickers manifest
// DO NOT EDIT - Generated by scripts/generate-manifest.py

import type { Emoji } from '../composables/useEmojis'

export const stickers: Emoji[] = [
"""
    for emoji in emojis:
        ts_content += f"""  {{
    id: '{emoji['id']}',
    name: '{emoji['name']}',
    emotion: '{emoji['emotion']}',
    format: '{emoji['format']}',
    character: '{emoji['character']}',
    path: '{emoji['path']}'
  }},\n"""

    ts_content += """]

export const STICKERS_COUNT = stickers.length
"""
    return ts_content

if __name__ == '__main__':
    print('🔍 Scanning stickers...')
    emojis = scan_stickers()
    print(f'✅ Found {len(emojis)} stickers')

    print('📝 Generating TypeScript manifest...')
    ts_content = generate_ts_file(emojis)

    # Write to src/data/stickers.ts
    output_dir = Path('src/data')
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / 'stickers.ts'

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(ts_content)

    print(f'✅ Manifest written to {output_file}')

    # Print character stats
    char_counts = {}
    for e in emojis:
        char = e['character']
        char_counts[char] = char_counts.get(char, 0) + 1

    print(f'\n📊 Characters:')
    for char, count in sorted(char_counts.items()):
        name = CHARACTER_NAMES.get(char, char)
        print(f'  {name}: {count}')
