#!/bin/bash

# Generate stickers manifest for EmoGdream

echo "// Auto-generated stickers manifest"
echo "// DO NOT EDIT - Generated by scripts/generate-manifest.sh"
echo ""
echo "import type { Emoji } from '../composables/useEmojis'"
echo ""
echo "export const stickers: Emoji[] = ["

# Process each character directory
for char_dir in public/stickers/*/; do
    char=$(basename "$char_dir")
    # Process each file in character directory
    for file in "$char_dir"/*.{png,gif,webp}; do
        [ -f "$file" ] || continue
        filename=$(basename "$file")
        ext="${filename##*.}"
        emotion="${filename#$char_}"
        emotion="${emotion%.$ext}"
        # Clean emotion name
        emotion=$(echo "$emotion" | sed 's/[?！·！!]//g' | xargs)
        [ -z "$emotion" ] && emotion="unknown"

        # Check available formats for this emotion
        webp_file=$(ls "$char_dir"/"${char}_${emotion}".webp 2>/dev/null | head -1)
        png_file=$(ls "$char_dir"/"${char}_${emotion}".png 2>/dev/null | head -1)
        gif_file=$(ls "$char_dir"/"${char}_${emotion}".gif 2>/dev/null | head -1)

        # Determine preferred format
        if [ -n "$webp_file" ]; then
            preferred="webp"
            use_file="$webp_file"
        elif [ -n "$png_file" ]; then
            preferred="png"
            use_file="$png_file"
        else
            preferred="gif"
            use_file="$gif_file"
        fi

        # Build formats array string
        formats="["
        [ -n "$webp_file" ] && formats="$formats'webp',"
        [ -n "$png_file" ] && formats="$formats'png',"
        [ -n "$gif_file" ] && formats="$formats'gif',"
        formats="${formats%,} ]"

        cat << EOF
  {
    id: '${char}_${emotion}_${preferred}',
    name: '$(basename "$use_file")',
    emotion: '${emotion}',
    format: '${preferred}',
    character: '${char}',
    path: '/stickers/${char}/$(basename "$use_file")',
    formats: $formats
  },
EOF
    done
done

echo "]"
echo ""
echo "export const STICKERS_COUNT = stickers.length"
