#!/usr/bin/env python3
"""
Generate stickers manifest for EmoGdream
Scans public/stickers/ directory and creates a TypeScript file with all emoji data
Tracks available formats and prefers webp when available
"""

from pathlib import Path

CHARACTER_NAMES = {
    'nina': 'Nina',
    'nijika': 'Nijika',
    'tomori': 'Tomori',
    'momoka': 'Momoka',
    'subaru': 'Subaru',
    'hitori': 'Hitori',
    'ikuyo': 'Ikuyo',
    'soyo': 'Soyo',
    'taki': 'Taki',
    'tomo': 'Tomo',
    'rupa': 'Rupa',
    'sakiko': 'Sakiko',
    'ryo': 'Ryo',
    'uika': 'Uika',
    'nyamu': 'Nyamu',
    'mutsumi': 'Mutsumi',
    'raana': 'Raana',
    'umiri': 'Umiri',
    'gbc': 'GBC',
    'anon': 'Anon',
    'KB': 'KB',
    'mana': 'Mana'
}

def scan_stickers():
    stickers_dir = Path('public/stickers')
    emoji_files = {}

    for char_dir in sorted(stickers_dir.iterdir()):
        if not char_dir.is_dir() or char_dir.name.startswith('.'):
            continue

        character = char_dir.name
        for file_path in sorted(char_dir.iterdir()):
            if file_path.suffix.lower() not in ['.png', '.gif', '.webp']:
                continue

            filename = file_path.name
            ext = file_path.suffix.lower().lstrip('.')
            emotion = filename.replace(f'{character}_', '').replace(f'.{ext}', '')
            emotion = emotion.replace('?', '').replace('!', '').replace('？', '').replace('·', '').replace('！', '').strip()
            if not emotion:
                emotion = 'unknown'

            key = (character, emotion)
            if key not in emoji_files:
                emoji_files[key] = {}
            emoji_files[key][ext] = filename

    emojis = []
    for (character, emotion), formats in sorted(emoji_files.items()):
        preferred_format = 'webp' if 'webp' in formats else ('png' if 'png' in formats else 'gif')
        filename = formats[preferred_format]

        emojis.append({
            'id': f'{character}_{emotion}_{preferred_format}',
            'name': filename,
            'emotion': emotion,
            'format': preferred_format,
            'character': character,
            'path': f'/stickers/{character}/{filename}',
            'formats': list(formats.keys())
        })

    return emojis

def generate_ts_file(emojis):
    ts_content = "// Auto-generated stickers manifest\\n"
    ts_content += "// DO NOT EDIT - Generated by scripts/generate-manifest.py\\n"
    ts_content += "\\nimport type { Emoji } from '../composables/useEmojis'\\n"
    ts_content += "\\nexport const stickers: Emoji[] = [\\n"

    for emoji in emojis:
        formats_list = ', '.join(f"'{f}'" for f in emoji['formats'])
        ts_content += f"""  {{
  id: '{emoji['id']}',
  name: '{emoji['name']}',
  emotion: '{emoji['emotion']}',
  format: '{emoji['format']}',
  character: '{emoji['character']}',
  path: '{emoji['path']}',
  formats: [{formats_list}]
}}," + '\\n'

    ts_content += "]\\n"
    ts_content += "export const STICKERS_COUNT = stickers.length\\n"
    return ts_content

if __name__ == '__main__':
    print('🔍 Scanning stickers...')
    emojis = scan_stickers()
    print(f'✅ Found {len(emojis)} stickers')

    print('📝 Generating TypeScript manifest...')
    ts_content = generate_ts_file(emojis)

    output_dir = Path('src/data')
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / 'stickers.ts'

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(ts_content)

    print(f'✅ Manifest written to {output_file}')

    char_counts = {}
    for e in emojis:
        char = e['character']
        char_counts[char] = char_counts.get(char, 0) + 1

    print('\\n📊 Characters:')
    for char, count in sorted(char_counts.items()):
        name = CHARACTER_NAMES.get(char, char)
        print(f'  {name}: {count}')

    webp_count = sum(1 for e in emojis if 'webp' in e['formats'])
    png_count = sum(1 for e in emojis if 'png' in e['formats'])
    gif_count = sum(1 for e in emojis if 'gif' in e['formats'])

    print('\\n📐 Format availability:')
    print(f'  WebP: {webp_count} emojis')
    print(f'  PNG: {png_count} emojis')
    print(f'  GIF: {gif_count} emojis')
