// Auto-generated stickers manifest
// DO NOT EDIT - Generated by scripts/generate-manifest.py

import type { Emoji } from '../composables/useEmojis'

export const stickers: Emoji[] = [
  {
    id: 'KB_kb_awkward_triple_png',
    name: 'kb_awkward_triple.png',
    emotion: 'kb_awkward_triple',
    format: 'png',
    character: 'KB',
    path: '/stickers/KB/kb_awkward_triple.png'
  },
  {
    id: 'KB_kb_eating_a_lot_png',
    name: 'kb_eating_a_lot.png',
    emotion: 'kb_eating_a_lot',
    format: 'png',
    character: 'KB',
    path: '/stickers/KB/kb_eating_a_lot.png'
  },
  {
    id: 'KB_kb_pat_head_png',
    name: 'kb_pat_head.png',
    emotion: 'kb_pat_head',
    format: 'png',
    character: 'KB',
    path: '/stickers/KB/kb_pat_head.png'
  },
  {
    id: 'KB_kb_snuggle_png',
    name: 'kb_snuggle.png',
    emotion: 'kb_snuggle',
    format: 'png',
    character: 'KB',
    path: '/stickers/KB/kb_snuggle.png'
  },
  {
    id: 'KB_kb_threaten_png',
    name: 'kb_threaten.png',
    emotion: 'kb_threaten',
    format: 'png',
    character: 'KB',
    path: '/stickers/KB/kb_threaten.png'
  },
  {
    id: 'KB_kb_wake_up_gif',
    name: 'kb_wake_up.gif',
    emotion: 'kb_wake_up',
    format: 'gif',
    character: 'KB',
    path: '/stickers/KB/kb_wake_up.gif'
  },
  {
    id: 'KB_kb_wake_up_png',
    name: 'kb_wake_up.png',
    emotion: 'kb_wake_up',
    format: 'png',
    character: 'KB',
    path: '/stickers/KB/kb_wake_up.png'
  },
  {
    id: 'KB_kb_wake_up_webp',
    name: 'kb_wake_up.webp',
    emotion: 'kb_wake_up',
    format: 'webp',
    character: 'KB',
    path: '/stickers/KB/kb_wake_up.webp'
  },
  {
    id: 'anon_cry_gif',
    name: 'anon_cry.gif',
    emotion: 'cry',
    format: 'gif',
    character: 'anon',
    path: '/stickers/anon/anon_cry.gif'
  },
  {
    id: 'anon_cry_png',
    name: 'anon_cry.png',
    emotion: 'cry',
    format: 'png',
    character: 'anon',
    path: '/stickers/anon/anon_cry.png'
  },
  {
    id: 'anon_cry_webp',
    name: 'anon_cry.webp',
    emotion: 'cry',
    format: 'webp',
    character: 'anon',
    path: '/stickers/anon/anon_cry.webp'
  },
  {
    id: 'anon_got_tickets_png',
    name: 'anon_got_tickets.png',
    emotion: 'got_tickets',
    format: 'png',
    character: 'anon',
    path: '/stickers/anon/anon_got_tickets.png'
  },
  {
    id: 'anon_hah_gif',
    name: 'anon_hah.gif',
    emotion: 'hah',
    format: 'gif',
    character: 'anon',
    path: '/stickers/anon/anon_hah.gif'
  },
  {
    id: 'anon_hah_png',
    name: 'anon_hah.png',
    emotion: 'hah',
    format: 'png',
    character: 'anon',
    path: '/stickers/anon/anon_hah.png'
  },
  {
    id: 'anon_hah_webp',
    name: 'anon_hah.webp',
    emotion: 'hah',
    format: 'webp',
    character: 'anon',
    path: '/stickers/anon/anon_hah.webp'
  },
  {
    id: 'anon_heart_gif',
    name: 'anon_heart.gif',
    emotion: 'heart',
    format: 'gif',
    character: 'anon',
    path: '/stickers/anon/anon_heart.gif'
  },
  {
    id: 'anon_heart_png',
    name: 'anon_heart.png',
    emotion: 'heart',
    format: 'png',
    character: 'anon',
    path: '/stickers/anon/anon_heart.png'
  },
  {
    id: 'anon_heart_webp',
    name: 'anon_heart.webp',
    emotion: 'heart',
    format: 'webp',
    character: 'anon',
    path: '/stickers/anon/anon_heart.webp'
  },
  {
    id: 'anon_love_png',
    name: 'anon_love.png',
    emotion: 'love',
    format: 'png',
    character: 'anon',
    path: '/stickers/anon/anon_love.png'
  },
  {
    id: 'anon_really_png',
    name: 'anon_really.png',
    emotion: 'really',
    format: 'png',
    character: 'anon',
    path: '/stickers/anon/anon_really.png'
  },
  {
    id: 'anon_see_you_on_sns_png',
    name: 'anon_see_you_on_sns.png',
    emotion: 'see_you_on_sns',
    format: 'png',
    character: 'anon',
    path: '/stickers/anon/anon_see_you_on_sns.png'
  },
  {
    id: 'anon_shocked_png',
    name: 'anon_shocked.png',
    emotion: 'shocked',
    format: 'png',
    character: 'anon',
    path: '/stickers/anon/anon_shocked.png'
  },
  {
    id: 'anon_tgw_gif',
    name: 'anon_tgw.gif',
    emotion: 'tgw',
    format: 'gif',
    character: 'anon',
    path: '/stickers/anon/anon_tgw.gif'
  },
  {
    id: 'anon_tgw_png',
    name: 'anon_tgw.png',
    emotion: 'tgw',
    format: 'png',
    character: 'anon',
    path: '/stickers/anon/anon_tgw.png'
  },
  {
    id: 'anon_tgw_webp',
    name: 'anon_tgw.webp',
    emotion: 'tgw',
    format: 'webp',
    character: 'anon',
    path: '/stickers/anon/anon_tgw.webp'
  },
  {
    id: 'anon_tokino_tokyo_png',
    name: 'anon_tokino_anon_tokyo.png',
    emotion: 'tokino_tokyo',
    format: 'png',
    character: 'anon',
    path: '/stickers/anon/anon_tokino_anon_tokyo.png'
  },
  {
    id: 'anon_哈_png',
    name: '哈？！.png',
    emotion: '哈',
    format: 'png',
    character: 'anon',
    path: '/stickers/anon/哈？！.png'
  },
  {
    id: 'gbc_confused_png',
    name: 'gbc_confused.png',
    emotion: 'confused',
    format: 'png',
    character: 'gbc',
    path: '/stickers/gbc/gbc_confused.png'
  },
  {
    id: 'gbc_embrace_gif',
    name: 'gbc_embrace.gif',
    emotion: 'embrace',
    format: 'gif',
    character: 'gbc',
    path: '/stickers/gbc/gbc_embrace.gif'
  },
  {
    id: 'gbc_embrace_png',
    name: 'gbc_embrace.png',
    emotion: 'embrace',
    format: 'png',
    character: 'gbc',
    path: '/stickers/gbc/gbc_embrace.png'
  },
  {
    id: 'gbc_embrace_webp',
    name: 'gbc_embrace.webp',
    emotion: 'embrace',
    format: 'webp',
    character: 'gbc',
    path: '/stickers/gbc/gbc_embrace.webp'
  },
  {
    id: 'gbc_take_photo_png',
    name: 'gbc_take_photo.png',
    emotion: 'take_photo',
    format: 'png',
    character: 'gbc',
    path: '/stickers/gbc/gbc_take_photo.png'
  },
  {
    id: 'gbc_what_gif',
    name: 'gbc_what.gif',
    emotion: 'what',
    format: 'gif',
    character: 'gbc',
    path: '/stickers/gbc/gbc_what.gif'
  },
  {
    id: 'gbc_what_png',
    name: 'gbc_what.png',
    emotion: 'what',
    format: 'png',
    character: 'gbc',
    path: '/stickers/gbc/gbc_what.png'
  },
  {
    id: 'gbc_what_webp',
    name: 'gbc_what.webp',
    emotion: 'what',
    format: 'webp',
    character: 'gbc',
    path: '/stickers/gbc/gbc_what.webp'
  },
  {
    id: 'hitori_apologize_png',
    name: 'hitori_apologize.png',
    emotion: 'apologize',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_apologize.png'
  },
  {
    id: 'hitori_expect_png',
    name: 'hitori_expect.png',
    emotion: 'expect',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_expect.png'
  },
  {
    id: 'hitori_fear_gif',
    name: 'hitori_fear.gif',
    emotion: 'fear',
    format: 'gif',
    character: 'hitori',
    path: '/stickers/hitori/hitori_fear.gif'
  },
  {
    id: 'hitori_fear_png',
    name: 'hitori_fear.png',
    emotion: 'fear',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_fear.png'
  },
  {
    id: 'hitori_fear_webp',
    name: 'hitori_fear.webp',
    emotion: 'fear',
    format: 'webp',
    character: 'hitori',
    path: '/stickers/hitori/hitori_fear.webp'
  },
  {
    id: 'hitori_headache_png',
    name: 'hitori_headache.png',
    emotion: 'headache',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_headache.png'
  },
  {
    id: 'hitori_hit_png',
    name: 'hitori_hit.png',
    emotion: 'hit',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_hit.png'
  },
  {
    id: 'hitori_let_me_see_gif',
    name: 'hitori_let_me_see.gif',
    emotion: 'let_me_see',
    format: 'gif',
    character: 'hitori',
    path: '/stickers/hitori/hitori_let_me_see.gif'
  },
  {
    id: 'hitori_let_me_see_png',
    name: 'hitori_let_me_see.png',
    emotion: 'let_me_see',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_let_me_see.png'
  },
  {
    id: 'hitori_let_me_see_webp',
    name: 'hitori_let_me_see.webp',
    emotion: 'let_me_see',
    format: 'webp',
    character: 'hitori',
    path: '/stickers/hitori/hitori_let_me_see.webp'
  },
  {
    id: 'hitori_no_gif',
    name: 'hitori_no.gif',
    emotion: 'no',
    format: 'gif',
    character: 'hitori',
    path: '/stickers/hitori/hitori_no.gif'
  },
  {
    id: 'hitori_no_png',
    name: 'hitori_no.png',
    emotion: 'no',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_no.png'
  },
  {
    id: 'hitori_no_webp',
    name: 'hitori_no.webp',
    emotion: 'no',
    format: 'webp',
    character: 'hitori',
    path: '/stickers/hitori/hitori_no.webp'
  },
  {
    id: 'hitori_no_thanks_gif',
    name: 'hitori_no_thanks.gif',
    emotion: 'no_thanks',
    format: 'gif',
    character: 'hitori',
    path: '/stickers/hitori/hitori_no_thanks.gif'
  },
  {
    id: 'hitori_no_thanks_png',
    name: 'hitori_no_thanks.png',
    emotion: 'no_thanks',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_no_thanks.png'
  },
  {
    id: 'hitori_no_thanks_webp',
    name: 'hitori_no_thanks.webp',
    emotion: 'no_thanks',
    format: 'webp',
    character: 'hitori',
    path: '/stickers/hitori/hitori_no_thanks.webp'
  },
  {
    id: 'hitori_oh_no_png',
    name: 'hitori_oh_no.png',
    emotion: 'oh_no',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_oh_no.png'
  },
  {
    id: 'hitori_peeking_png',
    name: 'hitori_peeking.png',
    emotion: 'peeking',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_peeking.png'
  },
  {
    id: 'hitori_please_png',
    name: 'hitori_please.png',
    emotion: 'please',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_please.png'
  },
  {
    id: 'hitori_poke_gif',
    name: 'hitori_poke.gif',
    emotion: 'poke',
    format: 'gif',
    character: 'hitori',
    path: '/stickers/hitori/hitori_poke.gif'
  },
  {
    id: 'hitori_poke_png',
    name: 'hitori_poke.png',
    emotion: 'poke',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_poke.png'
  },
  {
    id: 'hitori_poke_webp',
    name: 'hitori_poke.webp',
    emotion: 'poke',
    format: 'webp',
    character: 'hitori',
    path: '/stickers/hitori/hitori_poke.webp'
  },
  {
    id: 'hitori_scared_png',
    name: 'hitori_scared.png',
    emotion: 'scared',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_scared.png'
  },
  {
    id: 'hitori_shy_png',
    name: 'hitori_shy.png',
    emotion: 'shy',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_shy.png'
  },
  {
    id: 'hitori_social_anxiety_png',
    name: 'hitori_social_anxiety.png',
    emotion: 'social_anxiety',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_social_anxiety.png'
  },
  {
    id: 'hitori_soul_ascend_png',
    name: 'hitori_soul_ascend.png',
    emotion: 'soul_ascend',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_soul_ascend.png'
  },
  {
    id: 'hitori_tap_gif',
    name: 'hitori_tap.gif',
    emotion: 'tap',
    format: 'gif',
    character: 'hitori',
    path: '/stickers/hitori/hitori_tap.gif'
  },
  {
    id: 'hitori_tap_png',
    name: 'hitori_tap.png',
    emotion: 'tap',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_tap.png'
  },
  {
    id: 'hitori_tap_webp',
    name: 'hitori_tap.webp',
    emotion: 'tap',
    format: 'webp',
    character: 'hitori',
    path: '/stickers/hitori/hitori_tap.webp'
  },
  {
    id: 'hitori_tired_png',
    name: 'hitori_tired.png',
    emotion: 'tired',
    format: 'png',
    character: 'hitori',
    path: '/stickers/hitori/hitori_tired.png'
  },
  {
    id: 'ikuyo_clap_png',
    name: 'ikuyo_clap.png',
    emotion: 'clap',
    format: 'png',
    character: 'ikuyo',
    path: '/stickers/ikuyo/ikuyo_clap.png'
  },
  {
    id: 'ikuyo_cute_png',
    name: 'ikuyo_cute.png',
    emotion: 'cute',
    format: 'png',
    character: 'ikuyo',
    path: '/stickers/ikuyo/ikuyo_cute.png'
  },
  {
    id: 'ikuyo_lose_color_png',
    name: 'ikuyo_lose_color.png',
    emotion: 'lose_color',
    format: 'png',
    character: 'ikuyo',
    path: '/stickers/ikuyo/ikuyo_lose_color.png'
  },
  {
    id: 'ikuyo_moved_png',
    name: 'ikuyo_moved.png',
    emotion: 'moved',
    format: 'png',
    character: 'ikuyo',
    path: '/stickers/ikuyo/ikuyo_moved.png'
  },
  {
    id: 'ikuyo_question_png',
    name: 'ikuyo_question.png',
    emotion: 'question',
    format: 'png',
    character: 'ikuyo',
    path: '/stickers/ikuyo/ikuyo_question.png'
  },
  {
    id: 'ikuyo_raise_hands_png',
    name: 'ikuyo_raise_hands.png',
    emotion: 'raise_hands',
    format: 'png',
    character: 'ikuyo',
    path: '/stickers/ikuyo/ikuyo_raise_hands.png'
  },
  {
    id: 'ikuyo_scared_png',
    name: 'ikuyo_scared.png',
    emotion: 'scared',
    format: 'png',
    character: 'ikuyo',
    path: '/stickers/ikuyo/ikuyo_scared.png'
  },
  {
    id: 'ikuyo_smile_png',
    name: 'ikuyo_smile.png',
    emotion: 'smile',
    format: 'png',
    character: 'ikuyo',
    path: '/stickers/ikuyo/ikuyo_smile.png'
  },
  {
    id: 'ikuyo_star_eyes_gif',
    name: 'ikuyo_star_eyes.gif',
    emotion: 'star_eyes',
    format: 'gif',
    character: 'ikuyo',
    path: '/stickers/ikuyo/ikuyo_star_eyes.gif'
  },
  {
    id: 'ikuyo_star_eyes_png',
    name: 'ikuyo_star_eyes.png',
    emotion: 'star_eyes',
    format: 'png',
    character: 'ikuyo',
    path: '/stickers/ikuyo/ikuyo_star_eyes.png'
  },
  {
    id: 'ikuyo_star_eyes_webp',
    name: 'ikuyo_star_eyes.webp',
    emotion: 'star_eyes',
    format: 'webp',
    character: 'ikuyo',
    path: '/stickers/ikuyo/ikuyo_star_eyes.webp'
  },
  {
    id: 'ikuyo_wait_gif',
    name: 'ikuyo_wait.gif',
    emotion: 'wait',
    format: 'gif',
    character: 'ikuyo',
    path: '/stickers/ikuyo/ikuyo_wait.gif'
  },
  {
    id: 'ikuyo_wait_png',
    name: 'ikuyo_wait.png',
    emotion: 'wait',
    format: 'png',
    character: 'ikuyo',
    path: '/stickers/ikuyo/ikuyo_wait.png'
  },
  {
    id: 'ikuyo_wait_webp',
    name: 'ikuyo_wait.webp',
    emotion: 'wait',
    format: 'webp',
    character: 'ikuyo',
    path: '/stickers/ikuyo/ikuyo_wait.webp'
  },
  {
    id: 'ikuyo_what_to_do_png',
    name: 'ikuyo_what_to_do.png',
    emotion: 'what_to_do',
    format: 'png',
    character: 'ikuyo',
    path: '/stickers/ikuyo/ikuyo_what_to_do.png'
  },
  {
    id: 'ikuyo_wow_png',
    name: 'ikuyo_wow.png',
    emotion: 'wow',
    format: 'png',
    character: 'ikuyo',
    path: '/stickers/ikuyo/ikuyo_wow.png'
  },
  {
    id: 'mana_five_time_champion_png',
    name: 'mana_five_time_champion.png',
    emotion: 'five_time_champion',
    format: 'png',
    character: 'mana',
    path: '/stickers/mana/mana_five_time_champion.png'
  },
  {
    id: 'mana_share_with_you_png',
    name: 'mana_share_with_you.png',
    emotion: 'share_with_you',
    format: 'png',
    character: 'mana',
    path: '/stickers/mana/mana_share_with_you.png'
  },
  {
    id: 'mana_stretch_png',
    name: 'mana_stretch.png',
    emotion: 'stretch',
    format: 'png',
    character: 'mana',
    path: '/stickers/mana/mana_stretch.png'
  },
  {
    id: 'momoka_appear_gif',
    name: 'momoka_appear.gif',
    emotion: 'appear',
    format: 'gif',
    character: 'momoka',
    path: '/stickers/momoka/momoka_appear.gif'
  },
  {
    id: 'momoka_appear_png',
    name: 'momoka_appear.png',
    emotion: 'appear',
    format: 'png',
    character: 'momoka',
    path: '/stickers/momoka/momoka_appear.png'
  },
  {
    id: 'momoka_appear_webp',
    name: 'momoka_appear.webp',
    emotion: 'appear',
    format: 'webp',
    character: 'momoka',
    path: '/stickers/momoka/momoka_appear.webp'
  },
  {
    id: 'momoka_bleh_png',
    name: 'momoka_bleh.png',
    emotion: 'bleh',
    format: 'png',
    character: 'momoka',
    path: '/stickers/momoka/momoka_bleh.png'
  },
  {
    id: 'momoka_blush_png',
    name: 'momoka_blush.png',
    emotion: 'blush',
    format: 'png',
    character: 'momoka',
    path: '/stickers/momoka/momoka_blush.png'
  },
  {
    id: 'momoka_eww_png',
    name: 'momoka_eww.png',
    emotion: 'eww',
    format: 'png',
    character: 'momoka',
    path: '/stickers/momoka/momoka_eww.png'
  },
  {
    id: 'momoka_freak_out_gif',
    name: 'momoka_freak_out.gif',
    emotion: 'freak_out',
    format: 'gif',
    character: 'momoka',
    path: '/stickers/momoka/momoka_freak_out.gif'
  },
  {
    id: 'momoka_freak_out_png',
    name: 'momoka_freak_out.png',
    emotion: 'freak_out',
    format: 'png',
    character: 'momoka',
    path: '/stickers/momoka/momoka_freak_out.png'
  },
  {
    id: 'momoka_freak_out_webp',
    name: 'momoka_freak_out.webp',
    emotion: 'freak_out',
    format: 'webp',
    character: 'momoka',
    path: '/stickers/momoka/momoka_freak_out.webp'
  },
  {
    id: 'momoka_gagging_png',
    name: 'momoka_gagging.png',
    emotion: 'gagging',
    format: 'png',
    character: 'momoka',
    path: '/stickers/momoka/momoka_gagging.png'
  },
  {
    id: 'momoka_get_up_gif',
    name: 'momoka_get_up.gif',
    emotion: 'get_up',
    format: 'gif',
    character: 'momoka',
    path: '/stickers/momoka/momoka_get_up.gif'
  },
  {
    id: 'momoka_get_up_png',
    name: 'momoka_get_up.png',
    emotion: 'get_up',
    format: 'png',
    character: 'momoka',
    path: '/stickers/momoka/momoka_get_up.png'
  },
  {
    id: 'momoka_get_up_webp',
    name: 'momoka_get_up.webp',
    emotion: 'get_up',
    format: 'webp',
    character: 'momoka',
    path: '/stickers/momoka/momoka_get_up.webp'
  },
  {
    id: 'momoka_hah_png',
    name: 'momoka_hah.png',
    emotion: 'hah',
    format: 'png',
    character: 'momoka',
    path: '/stickers/momoka/momoka_hah.png'
  },
  {
    id: 'momoka_haha_png',
    name: 'momoka_haha.png',
    emotion: 'haha',
    format: 'png',
    character: 'momoka',
    path: '/stickers/momoka/momoka_haha.png'
  },
  {
    id: 'momoka_peek_gif',
    name: 'momoka_peek.gif',
    emotion: 'peek',
    format: 'gif',
    character: 'momoka',
    path: '/stickers/momoka/momoka_peek.gif'
  },
  {
    id: 'momoka_peek_png',
    name: 'momoka_peek.png',
    emotion: 'peek',
    format: 'png',
    character: 'momoka',
    path: '/stickers/momoka/momoka_peek.png'
  },
  {
    id: 'momoka_peek_webp',
    name: 'momoka_peek.webp',
    emotion: 'peek',
    format: 'webp',
    character: 'momoka',
    path: '/stickers/momoka/momoka_peek.webp'
  },
  {
    id: 'momoka_pull_someone_gif',
    name: 'momoka_pull_someone.gif',
    emotion: 'pull_someone',
    format: 'gif',
    character: 'momoka',
    path: '/stickers/momoka/momoka_pull_someone.gif'
  },
  {
    id: 'momoka_pull_someone_png',
    name: 'momoka_pull_someone.png',
    emotion: 'pull_someone',
    format: 'png',
    character: 'momoka',
    path: '/stickers/momoka/momoka_pull_someone.png'
  },
  {
    id: 'momoka_pull_someone_webp',
    name: 'momoka_pull_someone.webp',
    emotion: 'pull_someone',
    format: 'webp',
    character: 'momoka',
    path: '/stickers/momoka/momoka_pull_someone.webp'
  },
  {
    id: 'momoka_relax_png',
    name: 'momoka_relax.png',
    emotion: 'relax',
    format: 'png',
    character: 'momoka',
    path: '/stickers/momoka/momoka_relax.png'
  },
  {
    id: 'momoka_sleep_gif',
    name: 'momoka_sleep.gif',
    emotion: 'sleep',
    format: 'gif',
    character: 'momoka',
    path: '/stickers/momoka/momoka_sleep.gif'
  },
  {
    id: 'momoka_sleep_png',
    name: 'momoka_sleep.png',
    emotion: 'sleep',
    format: 'png',
    character: 'momoka',
    path: '/stickers/momoka/momoka_sleep.png'
  },
  {
    id: 'momoka_sleep_webp',
    name: 'momoka_sleep.webp',
    emotion: 'sleep',
    format: 'webp',
    character: 'momoka',
    path: '/stickers/momoka/momoka_sleep.webp'
  },
  {
    id: 'momoka_surprised_gif',
    name: 'momoka_surprised.gif',
    emotion: 'surprised',
    format: 'gif',
    character: 'momoka',
    path: '/stickers/momoka/momoka_surprised.gif'
  },
  {
    id: 'momoka_surprised_png',
    name: 'momoka_surprised.png',
    emotion: 'surprised',
    format: 'png',
    character: 'momoka',
    path: '/stickers/momoka/momoka_surprised.png'
  },
  {
    id: 'momoka_surprised_webp',
    name: 'momoka_surprised.webp',
    emotion: 'surprised',
    format: 'webp',
    character: 'momoka',
    path: '/stickers/momoka/momoka_surprised.webp'
  },
  {
    id: 'momoka_weep_png',
    name: 'momoka_weep.png',
    emotion: 'weep',
    format: 'png',
    character: 'momoka',
    path: '/stickers/momoka/momoka_weep.png'
  },
  {
    id: 'mutsumi_act_cute_gif',
    name: 'mutsumi_act_cute.gif',
    emotion: 'act_cute',
    format: 'gif',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_act_cute.gif'
  },
  {
    id: 'mutsumi_act_cute_png',
    name: 'mutsumi_act_cute.png',
    emotion: 'act_cute',
    format: 'png',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_act_cute.png'
  },
  {
    id: 'mutsumi_act_cute_webp',
    name: 'mutsumi_act_cute.webp',
    emotion: 'act_cute',
    format: 'webp',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_act_cute.webp'
  },
  {
    id: 'mutsumi_angry_gif',
    name: 'mutsumi_angry.gif',
    emotion: 'angry',
    format: 'gif',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_angry.gif'
  },
  {
    id: 'mutsumi_angry_png',
    name: 'mutsumi_angry.png',
    emotion: 'angry',
    format: 'png',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_angry.png'
  },
  {
    id: 'mutsumi_angry_webp',
    name: 'mutsumi_angry.webp',
    emotion: 'angry',
    format: 'webp',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_angry.webp'
  },
  {
    id: 'mutsumi_calling_me_gif',
    name: 'mutsumi_calling_me.gif',
    emotion: 'calling_me',
    format: 'gif',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_calling_me.gif'
  },
  {
    id: 'mutsumi_calling_me_png',
    name: 'mutsumi_calling_me.png',
    emotion: 'calling_me',
    format: 'png',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_calling_me.png'
  },
  {
    id: 'mutsumi_calling_me_webp',
    name: 'mutsumi_calling_me.webp',
    emotion: 'calling_me',
    format: 'webp',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_calling_me.webp'
  },
  {
    id: 'mutsumi_covering_mouth_smile_gif',
    name: 'mutsumi_covering_mouth_smile.gif',
    emotion: 'covering_mouth_smile',
    format: 'gif',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_covering_mouth_smile.gif'
  },
  {
    id: 'mutsumi_covering_mouth_smile_png',
    name: 'mutsumi_covering_mouth_smile.png',
    emotion: 'covering_mouth_smile',
    format: 'png',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_covering_mouth_smile.png'
  },
  {
    id: 'mutsumi_covering_mouth_smile_webp',
    name: 'mutsumi_covering_mouth_smile.webp',
    emotion: 'covering_mouth_smile',
    format: 'webp',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_covering_mouth_smile.webp'
  },
  {
    id: 'mutsumi_drink_beverage_gif',
    name: 'mutsumi_drink_beverage.gif',
    emotion: 'drink_beverage',
    format: 'gif',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_drink_beverage.gif'
  },
  {
    id: 'mutsumi_drink_beverage_png',
    name: 'mutsumi_drink_beverage.png',
    emotion: 'drink_beverage',
    format: 'png',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_drink_beverage.png'
  },
  {
    id: 'mutsumi_drink_beverage_webp',
    name: 'mutsumi_drink_beverage.webp',
    emotion: 'drink_beverage',
    format: 'webp',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_drink_beverage.webp'
  },
  {
    id: 'mutsumi_eh_png',
    name: 'mutsumi_eh.png',
    emotion: 'eh',
    format: 'png',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_eh.png'
  },
  {
    id: 'mutsumi_happy_png',
    name: 'mutsumi_happy.png',
    emotion: 'happy',
    format: 'png',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_happy.png'
  },
  {
    id: 'mutsumi_hug_png',
    name: 'mutsumi_hug.png',
    emotion: 'hug',
    format: 'png',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_hug.png'
  },
  {
    id: 'mutsumi_humph_png',
    name: 'mutsumi_humph.png',
    emotion: 'humph',
    format: 'png',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_humph.png'
  },
  {
    id: 'mutsumi_its_a_secret_png',
    name: 'mutsumi_its_a_secret.png',
    emotion: 'its_a_secret',
    format: 'png',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_its_a_secret.png'
  },
  {
    id: 'mutsumi_rainy_day_png',
    name: 'mutsumi_rainy_day.png',
    emotion: 'rainy_day',
    format: 'png',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_rainy_day.png'
  },
  {
    id: 'mutsumi_singing_png',
    name: 'mutsumi_singing.png',
    emotion: 'singing',
    format: 'png',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_singing.png'
  },
  {
    id: 'mutsumi_water_cucumber_gif',
    name: 'mutsumi_water_cucumber.gif',
    emotion: 'water_cucumber',
    format: 'gif',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_water_cucumber.gif'
  },
  {
    id: 'mutsumi_water_cucumber_png',
    name: 'mutsumi_water_cucumber.png',
    emotion: 'water_cucumber',
    format: 'png',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_water_cucumber.png'
  },
  {
    id: 'mutsumi_water_cucumber_webp',
    name: 'mutsumi_water_cucumber.webp',
    emotion: 'water_cucumber',
    format: 'webp',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_water_cucumber.webp'
  },
  {
    id: 'mutsumi_why_suddenly_png',
    name: 'mutsumi_why_suddenly.png',
    emotion: 'why_suddenly',
    format: 'png',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_why_suddenly.png'
  },
  {
    id: 'mutsumi_wink_gif',
    name: 'mutsumi_wink.gif',
    emotion: 'wink',
    format: 'gif',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_wink.gif'
  },
  {
    id: 'mutsumi_wink_png',
    name: 'mutsumi_wink.png',
    emotion: 'wink',
    format: 'png',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_wink.png'
  },
  {
    id: 'mutsumi_wink_webp',
    name: 'mutsumi_wink.webp',
    emotion: 'wink',
    format: 'webp',
    character: 'mutsumi',
    path: '/stickers/mutsumi/mutsumi_wink.webp'
  },
  {
    id: 'nijika_awkward_png',
    name: 'nijika_awkward.png',
    emotion: 'awkward',
    format: 'png',
    character: 'nijika',
    path: '/stickers/nijika/nijika_awkward.png'
  },
  {
    id: 'nijika_cheer_png',
    name: 'nijika_cheer.png',
    emotion: 'cheer',
    format: 'png',
    character: 'nijika',
    path: '/stickers/nijika/nijika_cheer.png'
  },
  {
    id: 'nijika_cry_gif',
    name: 'nijika_cry.gif',
    emotion: 'cry',
    format: 'gif',
    character: 'nijika',
    path: '/stickers/nijika/nijika_cry.gif'
  },
  {
    id: 'nijika_cry_png',
    name: 'nijika_cry.png',
    emotion: 'cry',
    format: 'png',
    character: 'nijika',
    path: '/stickers/nijika/nijika_cry.png'
  },
  {
    id: 'nijika_cry_webp',
    name: 'nijika_cry.webp',
    emotion: 'cry',
    format: 'webp',
    character: 'nijika',
    path: '/stickers/nijika/nijika_cry.webp'
  },
  {
    id: 'nijika_good_girl_png',
    name: 'nijika_good_girl.png',
    emotion: 'good_girl',
    format: 'png',
    character: 'nijika',
    path: '/stickers/nijika/nijika_good_girl.png'
  },
  {
    id: 'nijika_great_gif',
    name: 'nijika_great.gif',
    emotion: 'great',
    format: 'gif',
    character: 'nijika',
    path: '/stickers/nijika/nijika_great.gif'
  },
  {
    id: 'nijika_great_png',
    name: 'nijika_great.png',
    emotion: 'great',
    format: 'png',
    character: 'nijika',
    path: '/stickers/nijika/nijika_great.png'
  },
  {
    id: 'nijika_great_webp',
    name: 'nijika_great.webp',
    emotion: 'great',
    format: 'webp',
    character: 'nijika',
    path: '/stickers/nijika/nijika_great.webp'
  },
  {
    id: 'nijika_hehe_gif',
    name: 'nijika_hehe.gif',
    emotion: 'hehe',
    format: 'gif',
    character: 'nijika',
    path: '/stickers/nijika/nijika_hehe.gif'
  },
  {
    id: 'nijika_hehe_png',
    name: 'nijika_hehe.png',
    emotion: 'hehe',
    format: 'png',
    character: 'nijika',
    path: '/stickers/nijika/nijika_hehe.png'
  },
  {
    id: 'nijika_hehe_webp',
    name: 'nijika_hehe.webp',
    emotion: 'hehe',
    format: 'webp',
    character: 'nijika',
    path: '/stickers/nijika/nijika_hehe.webp'
  },
  {
    id: 'nijika_huh_png',
    name: 'nijika_huh.png',
    emotion: 'huh',
    format: 'png',
    character: 'nijika',
    path: '/stickers/nijika/nijika_huh.png'
  },
  {
    id: 'nijika_let_me_listen_png',
    name: 'nijika_let_me_listen.png',
    emotion: 'let_me_listen',
    format: 'png',
    character: 'nijika',
    path: '/stickers/nijika/nijika_let_me_listen.png'
  },
  {
    id: 'nijika_pouting_png',
    name: 'nijika_pouting.png',
    emotion: 'pouting',
    format: 'png',
    character: 'nijika',
    path: '/stickers/nijika/nijika_pouting.png'
  },
  {
    id: 'nijika_shh_png',
    name: 'nijika_shh.png',
    emotion: 'shh',
    format: 'png',
    character: 'nijika',
    path: '/stickers/nijika/nijika_shh.png'
  },
  {
    id: 'nijika_shocked_png',
    name: 'nijika_shocked.png',
    emotion: 'shocked',
    format: 'png',
    character: 'nijika',
    path: '/stickers/nijika/nijika_shocked.png'
  },
  {
    id: 'nina_awkward_gif',
    name: 'nina_awkward.gif',
    emotion: 'awkward',
    format: 'gif',
    character: 'nina',
    path: '/stickers/nina/nina_awkward.gif'
  },
  {
    id: 'nina_awkward_webp',
    name: 'nina_awkward.webp',
    emotion: 'awkward',
    format: 'webp',
    character: 'nina',
    path: '/stickers/nina/nina_awkward.webp'
  },
  {
    id: 'nina_being_dragged_gif',
    name: 'nina_being_dragged.gif',
    emotion: 'being_dragged',
    format: 'gif',
    character: 'nina',
    path: '/stickers/nina/nina_being_dragged.gif'
  },
  {
    id: 'nina_being_dragged_png',
    name: 'nina_being_dragged.png',
    emotion: 'being_dragged',
    format: 'png',
    character: 'nina',
    path: '/stickers/nina/nina_being_dragged.png'
  },
  {
    id: 'nina_being_dragged_webp',
    name: 'nina_being_dragged.webp',
    emotion: 'being_dragged',
    format: 'webp',
    character: 'nina',
    path: '/stickers/nina/nina_being_dragged.webp'
  },
  {
    id: 'nina_cannot_watch_png',
    name: 'nina_cannot_watch.png',
    emotion: 'cannot_watch',
    format: 'png',
    character: 'nina',
    path: '/stickers/nina/nina_cannot_watch.png'
  },
  {
    id: 'nina_cry_png',
    name: 'nina_cry.png',
    emotion: 'cry',
    format: 'png',
    character: 'nina',
    path: '/stickers/nina/nina_cry.png'
  },
  {
    id: 'nina_eating_gif',
    name: 'nina_eating.gif',
    emotion: 'eating',
    format: 'gif',
    character: 'nina',
    path: '/stickers/nina/nina_eating.gif'
  },
  {
    id: 'nina_eating_png',
    name: 'nina_eating.png',
    emotion: 'eating',
    format: 'png',
    character: 'nina',
    path: '/stickers/nina/nina_eating.png'
  },
  {
    id: 'nina_eating_webp',
    name: 'nina_eating.webp',
    emotion: 'eating',
    format: 'webp',
    character: 'nina',
    path: '/stickers/nina/nina_eating.webp'
  },
  {
    id: 'nina_evil_smile_png',
    name: 'nina_evil_smile.png',
    emotion: 'evil_smile',
    format: 'png',
    character: 'nina',
    path: '/stickers/nina/nina_evil_smile.png'
  },
  {
    id: 'nina_hehe_gif',
    name: 'nina_hehe.gif',
    emotion: 'hehe',
    format: 'gif',
    character: 'nina',
    path: '/stickers/nina/nina_hehe.gif'
  },
  {
    id: 'nina_hehe_webp',
    name: 'nina_hehe.webp',
    emotion: 'hehe',
    format: 'webp',
    character: 'nina',
    path: '/stickers/nina/nina_hehe.webp'
  },
  {
    id: 'nina_one_gif',
    name: 'nina_one.gif',
    emotion: 'one',
    format: 'gif',
    character: 'nina',
    path: '/stickers/nina/nina_one.gif'
  },
  {
    id: 'nina_one_png',
    name: 'nina_one.png',
    emotion: 'one',
    format: 'png',
    character: 'nina',
    path: '/stickers/nina/nina_one.png'
  },
  {
    id: 'nina_one_webp',
    name: 'nina_one.webp',
    emotion: 'one',
    format: 'webp',
    character: 'nina',
    path: '/stickers/nina/nina_one.webp'
  },
  {
    id: 'nina_pinch_face_gif',
    name: 'nina_pinch_face.gif',
    emotion: 'pinch_face',
    format: 'gif',
    character: 'nina',
    path: '/stickers/nina/nina_pinch_face.gif'
  },
  {
    id: 'nina_pinch_face_png',
    name: 'nina_pinch_face.png',
    emotion: 'pinch_face',
    format: 'png',
    character: 'nina',
    path: '/stickers/nina/nina_pinch_face.png'
  },
  {
    id: 'nina_pinch_face_webp',
    name: 'nina_pinch_face.webp',
    emotion: 'pinch_face',
    format: 'webp',
    character: 'nina',
    path: '/stickers/nina/nina_pinch_face.webp'
  },
  {
    id: 'nina_rock_png',
    name: 'nina_rock.png',
    emotion: 'rock',
    format: 'png',
    character: 'nina',
    path: '/stickers/nina/nina_rock.png'
  },
  {
    id: 'nina_rub_head_gif',
    name: 'nina_rub_head.gif',
    emotion: 'rub_head',
    format: 'gif',
    character: 'nina',
    path: '/stickers/nina/nina_rub_head.gif'
  },
  {
    id: 'nina_rub_head_png',
    name: 'nina_rub_head.png',
    emotion: 'rub_head',
    format: 'png',
    character: 'nina',
    path: '/stickers/nina/nina_rub_head.png'
  },
  {
    id: 'nina_rub_head_webp',
    name: 'nina_rub_head.webp',
    emotion: 'rub_head',
    format: 'webp',
    character: 'nina',
    path: '/stickers/nina/nina_rub_head.webp'
  },
  {
    id: 'nina_scream_png',
    name: 'nina_scream.png',
    emotion: 'scream',
    format: 'png',
    character: 'nina',
    path: '/stickers/nina/nina_scream.png'
  },
  {
    id: 'nina_slap_table_gif',
    name: 'nina_slap_table.gif',
    emotion: 'slap_table',
    format: 'gif',
    character: 'nina',
    path: '/stickers/nina/nina_slap_table.gif'
  },
  {
    id: 'nina_slap_table_png',
    name: 'nina_slap_table.png',
    emotion: 'slap_table',
    format: 'png',
    character: 'nina',
    path: '/stickers/nina/nina_slap_table.png'
  },
  {
    id: 'nina_slap_table_webp',
    name: 'nina_slap_table.webp',
    emotion: 'slap_table',
    format: 'webp',
    character: 'nina',
    path: '/stickers/nina/nina_slap_table.webp'
  },
  {
    id: 'nina_stubborn_png',
    name: 'nina_stubborn.png',
    emotion: 'stubborn',
    format: 'png',
    character: 'nina',
    path: '/stickers/nina/nina_stubborn.png'
  },
  {
    id: 'nina_stunned_png',
    name: 'nina_stunned.png',
    emotion: 'stunned',
    format: 'png',
    character: 'nina',
    path: '/stickers/nina/nina_stunned.png'
  },
  {
    id: 'nyamu_add_friend_png',
    name: 'nyamu_add_friend.png',
    emotion: 'add_friend',
    format: 'png',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_add_friend.png'
  },
  {
    id: 'nyamu_aggrieved_png',
    name: 'nyamu_aggrieved.png',
    emotion: 'aggrieved',
    format: 'png',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_aggrieved.png'
  },
  {
    id: 'nyamu_could_it_be_png',
    name: 'nyamu_could_it_be.png',
    emotion: 'could_it_be',
    format: 'png',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_could_it_be.png'
  },
  {
    id: 'nyamu_good_evening_meow_gif',
    name: 'nyamu_good_evening_meow.gif',
    emotion: 'good_evening_meow',
    format: 'gif',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_good_evening_meow.gif'
  },
  {
    id: 'nyamu_good_evening_meow_png',
    name: 'nyamu_good_evening_meow.png',
    emotion: 'good_evening_meow',
    format: 'png',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_good_evening_meow.png'
  },
  {
    id: 'nyamu_good_evening_meow_webp',
    name: 'nyamu_good_evening_meow.webp',
    emotion: 'good_evening_meow',
    format: 'webp',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_good_evening_meow.webp'
  },
  {
    id: 'nyamu_goodbye_gif',
    name: 'nyamu_goodbye.gif',
    emotion: 'goodbye',
    format: 'gif',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_goodbye.gif'
  },
  {
    id: 'nyamu_goodbye_png',
    name: 'nyamu_goodbye.png',
    emotion: 'goodbye',
    format: 'png',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_goodbye.png'
  },
  {
    id: 'nyamu_goodbye_webp',
    name: 'nyamu_goodbye.webp',
    emotion: 'goodbye',
    format: 'webp',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_goodbye.webp'
  },
  {
    id: 'nyamu_happy_meow_gif',
    name: 'nyamu_happy_meow.gif',
    emotion: 'happy_meow',
    format: 'gif',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_happy_meow.gif'
  },
  {
    id: 'nyamu_happy_meow_png',
    name: 'nyamu_happy_meow.png',
    emotion: 'happy_meow',
    format: 'png',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_happy_meow.png'
  },
  {
    id: 'nyamu_happy_meow_webp',
    name: 'nyamu_happy_meow.webp',
    emotion: 'happy_meow',
    format: 'webp',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_happy_meow.webp'
  },
  {
    id: 'nyamu_look_around_gif',
    name: 'nyamu_look_around.gif',
    emotion: 'look_around',
    format: 'gif',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_look_around.gif'
  },
  {
    id: 'nyamu_look_around_png',
    name: 'nyamu_look_around.png',
    emotion: 'look_around',
    format: 'png',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_look_around.png'
  },
  {
    id: 'nyamu_look_around_webp',
    name: 'nyamu_look_around.webp',
    emotion: 'look_around',
    format: 'webp',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_look_around.webp'
  },
  {
    id: 'nyamu_moved_to_tears_gif',
    name: 'nyamu_moved_to_tears.gif',
    emotion: 'moved_to_tears',
    format: 'gif',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_moved_to_tears.gif'
  },
  {
    id: 'nyamu_moved_to_tears_png',
    name: 'nyamu_moved_to_tears.png',
    emotion: 'moved_to_tears',
    format: 'png',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_moved_to_tears.png'
  },
  {
    id: 'nyamu_moved_to_tears_webp',
    name: 'nyamu_moved_to_tears.webp',
    emotion: 'moved_to_tears',
    format: 'webp',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_moved_to_tears.webp'
  },
  {
    id: 'nyamu_naughty_png',
    name: 'nyamu_naughty.png',
    emotion: 'naughty',
    format: 'png',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_naughty.png'
  },
  {
    id: 'nyamu_oh_png',
    name: 'nyamu_oh.png',
    emotion: 'oh',
    format: 'png',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_oh.png'
  },
  {
    id: 'nyamu_please_meow_gif',
    name: 'nyamu_please_meow.gif',
    emotion: 'please_meow',
    format: 'gif',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_please_meow.gif'
  },
  {
    id: 'nyamu_please_meow_png',
    name: 'nyamu_please_meow.png',
    emotion: 'please_meow',
    format: 'png',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_please_meow.png'
  },
  {
    id: 'nyamu_please_meow_webp',
    name: 'nyamu_please_meow.webp',
    emotion: 'please_meow',
    format: 'webp',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_please_meow.webp'
  },
  {
    id: 'nyamu_remember_to_smile_png',
    name: 'nyamu_remember_to_smile.png',
    emotion: 'remember_to_smile',
    format: 'png',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_remember_to_smile.png'
  },
  {
    id: 'nyamu_sulking_png',
    name: 'nyamu_sulking.png',
    emotion: 'sulking',
    format: 'png',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_sulking.png'
  },
  {
    id: 'nyamu_wow_gif',
    name: 'nyamu_wow.gif',
    emotion: 'wow',
    format: 'gif',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_wow.gif'
  },
  {
    id: 'nyamu_wow_png',
    name: 'nyamu_wow.png',
    emotion: 'wow',
    format: 'png',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_wow.png'
  },
  {
    id: 'nyamu_wow_webp',
    name: 'nyamu_wow.webp',
    emotion: 'wow',
    format: 'webp',
    character: 'nyamu',
    path: '/stickers/nyamu/nyamu_wow.webp'
  },
  {
    id: 'raana_[良辰共此曲动态表情包_思考]_png',
    name: '[良辰共此曲动态表情包_思考].png',
    emotion: '[良辰共此曲动态表情包_思考]',
    format: 'png',
    character: 'raana',
    path: '/stickers/raana/[良辰共此曲动态表情包_思考].png'
  },
  {
    id: 'raana_found_prey_png',
    name: 'raana_found_prey.png',
    emotion: 'found_prey',
    format: 'png',
    character: 'raana',
    path: '/stickers/raana/raana_found_prey.png'
  },
  {
    id: 'raana_handshake_gif',
    name: 'raana_handshake.gif',
    emotion: 'handshake',
    format: 'gif',
    character: 'raana',
    path: '/stickers/raana/raana_handshake.gif'
  },
  {
    id: 'raana_handshake_png',
    name: 'raana_handshake.png',
    emotion: 'handshake',
    format: 'png',
    character: 'raana',
    path: '/stickers/raana/raana_handshake.png'
  },
  {
    id: 'raana_handshake_webp',
    name: 'raana_handshake.webp',
    emotion: 'handshake',
    format: 'webp',
    character: 'raana',
    path: '/stickers/raana/raana_handshake.webp'
  },
  {
    id: 'raana_hunting_mode_png',
    name: 'raana_hunting_mode.png',
    emotion: 'hunting_mode',
    format: 'png',
    character: 'raana',
    path: '/stickers/raana/raana_hunting_mode.png'
  },
  {
    id: 'raana_interesting_woman_png',
    name: 'raana_interesting_woman.png',
    emotion: 'interesting_woman',
    format: 'png',
    character: 'raana',
    path: '/stickers/raana/raana_interesting_woman.png'
  },
  {
    id: 'raana_just_woke_up_png',
    name: 'raana_just_woke_up.png',
    emotion: 'just_woke_up',
    format: 'png',
    character: 'raana',
    path: '/stickers/raana/raana_just_woke_up.png'
  },
  {
    id: 'raana_likes_matcha_png',
    name: 'raana_likes_matcha.png',
    emotion: 'likes_matcha',
    format: 'png',
    character: 'raana',
    path: '/stickers/raana/raana_likes_matcha.png'
  },
  {
    id: 'raana_matcha_parfait_png',
    name: 'raana_matcha_parfait.png',
    emotion: 'matcha_parfait',
    format: 'png',
    character: 'raana',
    path: '/stickers/raana/raana_matcha_parfait.png'
  },
  {
    id: 'raana_observe_gif',
    name: 'raana_observe.gif',
    emotion: 'observe',
    format: 'gif',
    character: 'raana',
    path: '/stickers/raana/raana_observe.gif'
  },
  {
    id: 'raana_observe_png',
    name: 'raana_observe.png',
    emotion: 'observe',
    format: 'png',
    character: 'raana',
    path: '/stickers/raana/raana_observe.png'
  },
  {
    id: 'raana_observe_webp',
    name: 'raana_observe.webp',
    emotion: 'observe',
    format: 'webp',
    character: 'raana',
    path: '/stickers/raana/raana_observe.webp'
  },
  {
    id: 'raana_pet_cat_gif',
    name: 'raana_pet_cat.gif',
    emotion: 'pet_cat',
    format: 'gif',
    character: 'raana',
    path: '/stickers/raana/raana_pet_cat.gif'
  },
  {
    id: 'raana_pet_cat_png',
    name: 'raana_pet_cat.png',
    emotion: 'pet_cat',
    format: 'png',
    character: 'raana',
    path: '/stickers/raana/raana_pet_cat.png'
  },
  {
    id: 'raana_pet_cat_webp',
    name: 'raana_pet_cat.webp',
    emotion: 'pet_cat',
    format: 'webp',
    character: 'raana',
    path: '/stickers/raana/raana_pet_cat.webp'
  },
  {
    id: 'raana_running_away_png',
    name: 'raana_running_away.png',
    emotion: 'running_away',
    format: 'png',
    character: 'raana',
    path: '/stickers/raana/raana_running_away.png'
  },
  {
    id: 'raana_surrounded_by_cats_png',
    name: 'raana_surrounded_by_cats.png',
    emotion: 'surrounded_by_cats',
    format: 'png',
    character: 'raana',
    path: '/stickers/raana/raana_surrounded_by_cats.png'
  },
  {
    id: 'raana_thinking_gif',
    name: 'raana_thinking.gif',
    emotion: 'thinking',
    format: 'gif',
    character: 'raana',
    path: '/stickers/raana/raana_thinking.gif'
  },
  {
    id: 'raana_thinking_png',
    name: 'raana_thinking.png',
    emotion: 'thinking',
    format: 'png',
    character: 'raana',
    path: '/stickers/raana/raana_thinking.png'
  },
  {
    id: 'raana_thinking_webp',
    name: 'raana_thinking.webp',
    emotion: 'thinking',
    format: 'webp',
    character: 'raana',
    path: '/stickers/raana/raana_thinking.webp'
  },
  {
    id: 'rupa_bye_png',
    name: 'rupa_bye.png',
    emotion: 'bye',
    format: 'png',
    character: 'rupa',
    path: '/stickers/rupa/rupa_bye.png'
  },
  {
    id: 'rupa_catch_box_gif',
    name: 'rupa_catch_box.gif',
    emotion: 'catch_box',
    format: 'gif',
    character: 'rupa',
    path: '/stickers/rupa/rupa_catch_box.gif'
  },
  {
    id: 'rupa_catch_box_png',
    name: 'rupa_catch_box.png',
    emotion: 'catch_box',
    format: 'png',
    character: 'rupa',
    path: '/stickers/rupa/rupa_catch_box.png'
  },
  {
    id: 'rupa_catch_box_webp',
    name: 'rupa_catch_box.webp',
    emotion: 'catch_box',
    format: 'webp',
    character: 'rupa',
    path: '/stickers/rupa/rupa_catch_box.webp'
  },
  {
    id: 'rupa_cheer_gif',
    name: 'rupa_cheer.gif',
    emotion: 'cheer',
    format: 'gif',
    character: 'rupa',
    path: '/stickers/rupa/rupa_cheer.gif'
  },
  {
    id: 'rupa_cheer_png',
    name: 'rupa_cheer.png',
    emotion: 'cheer',
    format: 'png',
    character: 'rupa',
    path: '/stickers/rupa/rupa_cheer.png'
  },
  {
    id: 'rupa_cheer_webp',
    name: 'rupa_cheer.webp',
    emotion: 'cheer',
    format: 'webp',
    character: 'rupa',
    path: '/stickers/rupa/rupa_cheer.webp'
  },
  {
    id: 'rupa_confident_png',
    name: 'rupa_confident.png',
    emotion: 'confident',
    format: 'png',
    character: 'rupa',
    path: '/stickers/rupa/rupa_confident.png'
  },
  {
    id: 'rupa_cooking_png',
    name: 'rupa_cooking.png',
    emotion: 'cooking',
    format: 'png',
    character: 'rupa',
    path: '/stickers/rupa/rupa_cooking.png'
  },
  {
    id: 'rupa_drive_gif',
    name: 'rupa_drive.gif',
    emotion: 'drive',
    format: 'gif',
    character: 'rupa',
    path: '/stickers/rupa/rupa_drive.gif'
  },
  {
    id: 'rupa_drive_png',
    name: 'rupa_drive.png',
    emotion: 'drive',
    format: 'png',
    character: 'rupa',
    path: '/stickers/rupa/rupa_drive.png'
  },
  {
    id: 'rupa_drive_webp',
    name: 'rupa_drive.webp',
    emotion: 'drive',
    format: 'webp',
    character: 'rupa',
    path: '/stickers/rupa/rupa_drive.webp'
  },
  {
    id: 'rupa_heart_png',
    name: 'rupa_heart.png',
    emotion: 'heart',
    format: 'png',
    character: 'rupa',
    path: '/stickers/rupa/rupa_heart.png'
  },
  {
    id: 'rupa_peace_sign_gif',
    name: 'rupa_peace_sign.gif',
    emotion: 'peace_sign',
    format: 'gif',
    character: 'rupa',
    path: '/stickers/rupa/rupa_peace_sign.gif'
  },
  {
    id: 'rupa_peace_sign_png',
    name: 'rupa_peace_sign.png',
    emotion: 'peace_sign',
    format: 'png',
    character: 'rupa',
    path: '/stickers/rupa/rupa_peace_sign.png'
  },
  {
    id: 'rupa_peace_sign_webp',
    name: 'rupa_peace_sign.webp',
    emotion: 'peace_sign',
    format: 'webp',
    character: 'rupa',
    path: '/stickers/rupa/rupa_peace_sign.webp'
  },
  {
    id: 'rupa_please_png',
    name: 'rupa_please.png',
    emotion: 'please',
    format: 'png',
    character: 'rupa',
    path: '/stickers/rupa/rupa_please.png'
  },
  {
    id: 'rupa_pop_out_gif',
    name: 'rupa_pop_out.gif',
    emotion: 'pop_out',
    format: 'gif',
    character: 'rupa',
    path: '/stickers/rupa/rupa_pop_out.gif'
  },
  {
    id: 'rupa_pop_out_png',
    name: 'rupa_pop_out.png',
    emotion: 'pop_out',
    format: 'png',
    character: 'rupa',
    path: '/stickers/rupa/rupa_pop_out.png'
  },
  {
    id: 'rupa_pop_out_webp',
    name: 'rupa_pop_out.webp',
    emotion: 'pop_out',
    format: 'webp',
    character: 'rupa',
    path: '/stickers/rupa/rupa_pop_out.webp'
  },
  {
    id: 'rupa_raise_hand_png',
    name: 'rupa_raise_hand.png',
    emotion: 'raise_hand',
    format: 'png',
    character: 'rupa',
    path: '/stickers/rupa/rupa_raise_hand.png'
  },
  {
    id: 'rupa_relieved_png',
    name: 'rupa_relieved.png',
    emotion: 'relieved',
    format: 'png',
    character: 'rupa',
    path: '/stickers/rupa/rupa_relieved.png'
  },
  {
    id: 'rupa_sigh_gif',
    name: 'rupa_sigh.gif',
    emotion: 'sigh',
    format: 'gif',
    character: 'rupa',
    path: '/stickers/rupa/rupa_sigh.gif'
  },
  {
    id: 'rupa_sigh_png',
    name: 'rupa_sigh.png',
    emotion: 'sigh',
    format: 'png',
    character: 'rupa',
    path: '/stickers/rupa/rupa_sigh.png'
  },
  {
    id: 'rupa_sigh_webp',
    name: 'rupa_sigh.webp',
    emotion: 'sigh',
    format: 'webp',
    character: 'rupa',
    path: '/stickers/rupa/rupa_sigh.webp'
  },
  {
    id: 'rupa_team_gif',
    name: 'rupa_team.gif',
    emotion: 'team',
    format: 'gif',
    character: 'rupa',
    path: '/stickers/rupa/rupa_team.gif'
  },
  {
    id: 'rupa_team_png',
    name: 'rupa_team.png',
    emotion: 'team',
    format: 'png',
    character: 'rupa',
    path: '/stickers/rupa/rupa_team.png'
  },
  {
    id: 'rupa_team_webp',
    name: 'rupa_team.webp',
    emotion: 'team',
    format: 'webp',
    character: 'rupa',
    path: '/stickers/rupa/rupa_team.webp'
  },
  {
    id: 'rupa_wiggle_gif',
    name: 'rupa_wiggle.gif',
    emotion: 'wiggle',
    format: 'gif',
    character: 'rupa',
    path: '/stickers/rupa/rupa_wiggle.gif'
  },
  {
    id: 'rupa_wiggle_png',
    name: 'rupa_wiggle.png',
    emotion: 'wiggle',
    format: 'png',
    character: 'rupa',
    path: '/stickers/rupa/rupa_wiggle.png'
  },
  {
    id: 'rupa_wiggle_webp',
    name: 'rupa_wiggle.webp',
    emotion: 'wiggle',
    format: 'webp',
    character: 'rupa',
    path: '/stickers/rupa/rupa_wiggle.webp'
  },
  {
    id: 'rupa_yay_png',
    name: 'rupa_yay.png',
    emotion: 'yay',
    format: 'png',
    character: 'rupa',
    path: '/stickers/rupa/rupa_yay.png'
  },
  {
    id: 'ryo_cool_png',
    name: 'ryo_cool.png',
    emotion: 'cool',
    format: 'png',
    character: 'ryo',
    path: '/stickers/ryo/ryo_cool.png'
  },
  {
    id: 'ryo_drink_tea_png',
    name: 'ryo_drink_tea.png',
    emotion: 'drink_tea',
    format: 'png',
    character: 'ryo',
    path: '/stickers/ryo/ryo_drink_tea.png'
  },
  {
    id: 'ryo_eat_grass_png',
    name: 'ryo_eat_grass.png',
    emotion: 'eat_grass',
    format: 'png',
    character: 'ryo',
    path: '/stickers/ryo/ryo_eat_grass.png'
  },
  {
    id: 'ryo_eating_a_lot_gif',
    name: 'ryo_eating_a_lot.gif',
    emotion: 'eating_a_lot',
    format: 'gif',
    character: 'ryo',
    path: '/stickers/ryo/ryo_eating_a_lot.gif'
  },
  {
    id: 'ryo_eating_a_lot_png',
    name: 'ryo_eating_a_lot.png',
    emotion: 'eating_a_lot',
    format: 'png',
    character: 'ryo',
    path: '/stickers/ryo/ryo_eating_a_lot.png'
  },
  {
    id: 'ryo_eating_a_lot_webp',
    name: 'ryo_eating_a_lot.webp',
    emotion: 'eating_a_lot',
    format: 'webp',
    character: 'ryo',
    path: '/stickers/ryo/ryo_eating_a_lot.webp'
  },
  {
    id: 'ryo_hehe_png',
    name: 'ryo_hehe.png',
    emotion: 'hehe',
    format: 'png',
    character: 'ryo',
    path: '/stickers/ryo/ryo_hehe.png'
  },
  {
    id: 'ryo_holding_laughter_png',
    name: 'ryo_holding_laughter.png',
    emotion: 'holding_laughter',
    format: 'png',
    character: 'ryo',
    path: '/stickers/ryo/ryo_holding_laughter.png'
  },
  {
    id: 'ryo_like_png',
    name: 'ryo_like.png',
    emotion: 'like',
    format: 'png',
    character: 'ryo',
    path: '/stickers/ryo/ryo_like.png'
  },
  {
    id: 'ryo_run_over_gif',
    name: 'ryo_run_over.gif',
    emotion: 'run_over',
    format: 'gif',
    character: 'ryo',
    path: '/stickers/ryo/ryo_run_over.gif'
  },
  {
    id: 'ryo_run_over_png',
    name: 'ryo_run_over.png',
    emotion: 'run_over',
    format: 'png',
    character: 'ryo',
    path: '/stickers/ryo/ryo_run_over.png'
  },
  {
    id: 'ryo_run_over_webp',
    name: 'ryo_run_over.webp',
    emotion: 'run_over',
    format: 'webp',
    character: 'ryo',
    path: '/stickers/ryo/ryo_run_over.webp'
  },
  {
    id: 'ryo_shy_gif',
    name: 'ryo_shy.gif',
    emotion: 'shy',
    format: 'gif',
    character: 'ryo',
    path: '/stickers/ryo/ryo_shy.gif'
  },
  {
    id: 'ryo_shy_webp',
    name: 'ryo_shy.webp',
    emotion: 'shy',
    format: 'webp',
    character: 'ryo',
    path: '/stickers/ryo/ryo_shy.webp'
  },
  {
    id: 'ryo_studying_png',
    name: 'ryo_studying.png',
    emotion: 'studying',
    format: 'png',
    character: 'ryo',
    path: '/stickers/ryo/ryo_studying.png'
  },
  {
    id: 'ryo_thinking_png',
    name: 'ryo_thinking.png',
    emotion: 'thinking',
    format: 'png',
    character: 'ryo',
    path: '/stickers/ryo/ryo_thinking.png'
  },
  {
    id: 'ryo_throw_money_png',
    name: 'ryo_throw_money.png',
    emotion: 'throw_money',
    format: 'png',
    character: 'ryo',
    path: '/stickers/ryo/ryo_throw_money.png'
  },
  {
    id: 'sakiko_applaud_gif',
    name: 'sakiko_applaud.gif',
    emotion: 'applaud',
    format: 'gif',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_applaud.gif'
  },
  {
    id: 'sakiko_applaud_png',
    name: 'sakiko_applaud.png',
    emotion: 'applaud',
    format: 'png',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_applaud.png'
  },
  {
    id: 'sakiko_applaud_webp',
    name: 'sakiko_applaud.webp',
    emotion: 'applaud',
    format: 'webp',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_applaud.webp'
  },
  {
    id: 'sakiko_cheer_gif',
    name: 'sakiko_cheer.gif',
    emotion: 'cheer',
    format: 'gif',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_cheer.gif'
  },
  {
    id: 'sakiko_cheer_png',
    name: 'sakiko_cheer.png',
    emotion: 'cheer',
    format: 'png',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_cheer.png'
  },
  {
    id: 'sakiko_cheer_webp',
    name: 'sakiko_cheer.webp',
    emotion: 'cheer',
    format: 'webp',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_cheer.webp'
  },
  {
    id: 'sakiko_clock_out_gif',
    name: 'sakiko_clock_out.gif',
    emotion: 'clock_out',
    format: 'gif',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_clock_out.gif'
  },
  {
    id: 'sakiko_clock_out_png',
    name: 'sakiko_clock_out.png',
    emotion: 'clock_out',
    format: 'png',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_clock_out.png'
  },
  {
    id: 'sakiko_clock_out_webp',
    name: 'sakiko_clock_out.webp',
    emotion: 'clock_out',
    format: 'webp',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_clock_out.webp'
  },
  {
    id: 'sakiko_cool_gif',
    name: 'sakiko_cool.gif',
    emotion: 'cool',
    format: 'gif',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_cool.gif'
  },
  {
    id: 'sakiko_cool_png',
    name: 'sakiko_cool.png',
    emotion: 'cool',
    format: 'png',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_cool.png'
  },
  {
    id: 'sakiko_cool_webp',
    name: 'sakiko_cool.webp',
    emotion: 'cool',
    format: 'webp',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_cool.webp'
  },
  {
    id: 'sakiko_delicious_png',
    name: 'sakiko_delicious.png',
    emotion: 'delicious',
    format: 'png',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_delicious.png'
  },
  {
    id: 'sakiko_god_descent_gif',
    name: 'sakiko_god_descent.gif',
    emotion: 'god_descent',
    format: 'gif',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_god_descent.gif'
  },
  {
    id: 'sakiko_god_descent_png',
    name: 'sakiko_god_descent.png',
    emotion: 'god_descent',
    format: 'png',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_god_descent.png'
  },
  {
    id: 'sakiko_god_descent_webp',
    name: 'sakiko_god_descent.webp',
    emotion: 'god_descent',
    format: 'webp',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_god_descent.webp'
  },
  {
    id: 'sakiko_i_have_something_to_say_png',
    name: 'sakiko_i_have_something_to_say.png',
    emotion: 'i_have_something_to_say',
    format: 'png',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_i_have_something_to_say.png'
  },
  {
    id: 'sakiko_no_gif',
    name: 'sakiko_no.gif',
    emotion: 'no',
    format: 'gif',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_no.gif'
  },
  {
    id: 'sakiko_no_png',
    name: 'sakiko_no.png',
    emotion: 'no',
    format: 'png',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_no.png'
  },
  {
    id: 'sakiko_no_webp',
    name: 'sakiko_no.webp',
    emotion: 'no',
    format: 'webp',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_no.webp'
  },
  {
    id: 'sakiko_pleased_png',
    name: 'sakiko_pleased.png',
    emotion: 'pleased',
    format: 'png',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_pleased.png'
  },
  {
    id: 'sakiko_reach_out_gif',
    name: 'sakiko_reach_out.gif',
    emotion: 'reach_out',
    format: 'gif',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_reach_out.gif'
  },
  {
    id: 'sakiko_reach_out_png',
    name: 'sakiko_reach_out.png',
    emotion: 'reach_out',
    format: 'png',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_reach_out.png'
  },
  {
    id: 'sakiko_reach_out_webp',
    name: 'sakiko_reach_out.webp',
    emotion: 'reach_out',
    format: 'webp',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_reach_out.webp'
  },
  {
    id: 'sakiko_sachiko_png',
    name: 'sakiko_sachiko.png',
    emotion: 'sachiko',
    format: 'png',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_sachiko.png'
  },
  {
    id: 'sakiko_shout_png',
    name: 'sakiko_shout.png',
    emotion: 'shout',
    format: 'png',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_shout.png'
  },
  {
    id: 'sakiko_toss_hair_png',
    name: 'sakiko_toss_hair.png',
    emotion: 'toss_hair',
    format: 'png',
    character: 'sakiko',
    path: '/stickers/sakiko/sakiko_toss_hair.png'
  },
  {
    id: 'soyo_angry_gif',
    name: 'soyo_angry.gif',
    emotion: 'angry',
    format: 'gif',
    character: 'soyo',
    path: '/stickers/soyo/soyo_angry.gif'
  },
  {
    id: 'soyo_angry_png',
    name: 'soyo_angry.png',
    emotion: 'angry',
    format: 'png',
    character: 'soyo',
    path: '/stickers/soyo/soyo_angry.png'
  },
  {
    id: 'soyo_angry_webp',
    name: 'soyo_angry.webp',
    emotion: 'angry',
    format: 'webp',
    character: 'soyo',
    path: '/stickers/soyo/soyo_angry.webp'
  },
  {
    id: 'soyo_cry_loudly_png',
    name: 'soyo_cry_loudly.png',
    emotion: 'cry_loudly',
    format: 'png',
    character: 'soyo',
    path: '/stickers/soyo/soyo_cry_loudly.png'
  },
  {
    id: 'soyo_cut_gif',
    name: 'soyo_cut.gif',
    emotion: 'cut',
    format: 'gif',
    character: 'soyo',
    path: '/stickers/soyo/soyo_cut.gif'
  },
  {
    id: 'soyo_cut_png',
    name: 'soyo_cut.png',
    emotion: 'cut',
    format: 'png',
    character: 'soyo',
    path: '/stickers/soyo/soyo_cut.png'
  },
  {
    id: 'soyo_cut_webp',
    name: 'soyo_cut.webp',
    emotion: 'cut',
    format: 'webp',
    character: 'soyo',
    path: '/stickers/soyo/soyo_cut.webp'
  },
  {
    id: 'soyo_giving_up_png',
    name: 'soyo_giving_up.png',
    emotion: 'giving_up',
    format: 'png',
    character: 'soyo',
    path: '/stickers/soyo/soyo_giving_up.png'
  },
  {
    id: 'soyo_play_with_hair_gif',
    name: 'soyo_play_with_hair.gif',
    emotion: 'play_with_hair',
    format: 'gif',
    character: 'soyo',
    path: '/stickers/soyo/soyo_play_with_hair.gif'
  },
  {
    id: 'soyo_play_with_hair_png',
    name: 'soyo_play_with_hair.png',
    emotion: 'play_with_hair',
    format: 'png',
    character: 'soyo',
    path: '/stickers/soyo/soyo_play_with_hair.png'
  },
  {
    id: 'soyo_play_with_hair_webp',
    name: 'soyo_play_with_hair.webp',
    emotion: 'play_with_hair',
    format: 'webp',
    character: 'soyo',
    path: '/stickers/soyo/soyo_play_with_hair.webp'
  },
  {
    id: 'soyo_send_message_png',
    name: 'soyo_send_message.png',
    emotion: 'send_message',
    format: 'png',
    character: 'soyo',
    path: '/stickers/soyo/soyo_send_message.png'
  },
  {
    id: 'soyo_serious_png',
    name: 'soyo_serious.png',
    emotion: 'serious',
    format: 'png',
    character: 'soyo',
    path: '/stickers/soyo/soyo_serious.png'
  },
  {
    id: 'soyo_smile_gif',
    name: 'soyo_smile.gif',
    emotion: 'smile',
    format: 'gif',
    character: 'soyo',
    path: '/stickers/soyo/soyo_smile.gif'
  },
  {
    id: 'soyo_smile_png',
    name: 'soyo_smile.png',
    emotion: 'smile',
    format: 'png',
    character: 'soyo',
    path: '/stickers/soyo/soyo_smile.png'
  },
  {
    id: 'soyo_smile_webp',
    name: 'soyo_smile.webp',
    emotion: 'smile',
    format: 'webp',
    character: 'soyo',
    path: '/stickers/soyo/soyo_smile.webp'
  },
  {
    id: 'soyo_stare_png',
    name: 'soyo_stare.png',
    emotion: 'stare',
    format: 'png',
    character: 'soyo',
    path: '/stickers/soyo/soyo_stare.png'
  },
  {
    id: 'soyo_surprised_png',
    name: 'soyo_surprised.png',
    emotion: 'surprised',
    format: 'png',
    character: 'soyo',
    path: '/stickers/soyo/soyo_surprised.png'
  },
  {
    id: 'soyo_thought_of_something_png',
    name: 'soyo_thought_of_something.png',
    emotion: 'thought_of_something',
    format: 'png',
    character: 'soyo',
    path: '/stickers/soyo/soyo_thought_of_something.png'
  },
  {
    id: 'soyo_why_png',
    name: 'soyo_why.png',
    emotion: 'why',
    format: 'png',
    character: 'soyo',
    path: '/stickers/soyo/soyo_why.png'
  },
  {
    id: 'subaru_eh_gif',
    name: 'subaru_eh.gif',
    emotion: 'eh',
    format: 'gif',
    character: 'subaru',
    path: '/stickers/subaru/subaru_eh.gif'
  },
  {
    id: 'subaru_eh_png',
    name: 'subaru_eh.png',
    emotion: 'eh',
    format: 'png',
    character: 'subaru',
    path: '/stickers/subaru/subaru_eh.png'
  },
  {
    id: 'subaru_eh_webp',
    name: 'subaru_eh.webp',
    emotion: 'eh',
    format: 'webp',
    character: 'subaru',
    path: '/stickers/subaru/subaru_eh.webp'
  },
  {
    id: 'subaru_finger_heart_png',
    name: 'subaru_finger_heart.png',
    emotion: 'finger_heart',
    format: 'png',
    character: 'subaru',
    path: '/stickers/subaru/subaru_finger_heart.png'
  },
  {
    id: 'subaru_grin_gif',
    name: 'subaru_grin.gif',
    emotion: 'grin',
    format: 'gif',
    character: 'subaru',
    path: '/stickers/subaru/subaru_grin.gif'
  },
  {
    id: 'subaru_grin_png',
    name: 'subaru_grin.png',
    emotion: 'grin',
    format: 'png',
    character: 'subaru',
    path: '/stickers/subaru/subaru_grin.png'
  },
  {
    id: 'subaru_grin_webp',
    name: 'subaru_grin.webp',
    emotion: 'grin',
    format: 'webp',
    character: 'subaru',
    path: '/stickers/subaru/subaru_grin.webp'
  },
  {
    id: 'subaru_group_gif',
    name: 'subaru_group.gif',
    emotion: 'group',
    format: 'gif',
    character: 'subaru',
    path: '/stickers/subaru/subaru_group.gif'
  },
  {
    id: 'subaru_group_png',
    name: 'subaru_group.png',
    emotion: 'group',
    format: 'png',
    character: 'subaru',
    path: '/stickers/subaru/subaru_group.png'
  },
  {
    id: 'subaru_group_webp',
    name: 'subaru_group.webp',
    emotion: 'group',
    format: 'webp',
    character: 'subaru',
    path: '/stickers/subaru/subaru_group.webp'
  },
  {
    id: 'subaru_happy_png',
    name: 'subaru_happy.png',
    emotion: 'happy',
    format: 'png',
    character: 'subaru',
    path: '/stickers/subaru/subaru_happy.png'
  },
  {
    id: 'subaru_mock_gif',
    name: 'subaru_mock.gif',
    emotion: 'mock',
    format: 'gif',
    character: 'subaru',
    path: '/stickers/subaru/subaru_mock.gif'
  },
  {
    id: 'subaru_mock_png',
    name: 'subaru_mock.png',
    emotion: 'mock',
    format: 'png',
    character: 'subaru',
    path: '/stickers/subaru/subaru_mock.png'
  },
  {
    id: 'subaru_mock_webp',
    name: 'subaru_mock.webp',
    emotion: 'mock',
    format: 'webp',
    character: 'subaru',
    path: '/stickers/subaru/subaru_mock.webp'
  },
  {
    id: 'subaru_offer_flowers_png',
    name: 'subaru_offer_flowers.png',
    emotion: 'offer_flowers',
    format: 'png',
    character: 'subaru',
    path: '/stickers/subaru/subaru_offer_flowers.png'
  },
  {
    id: 'subaru_peek_gif',
    name: 'subaru_peek.gif',
    emotion: 'peek',
    format: 'gif',
    character: 'subaru',
    path: '/stickers/subaru/subaru_peek.gif'
  },
  {
    id: 'subaru_peek_png',
    name: 'subaru_peek.png',
    emotion: 'peek',
    format: 'png',
    character: 'subaru',
    path: '/stickers/subaru/subaru_peek.png'
  },
  {
    id: 'subaru_peek_webp',
    name: 'subaru_peek.webp',
    emotion: 'peek',
    format: 'webp',
    character: 'subaru',
    path: '/stickers/subaru/subaru_peek.webp'
  },
  {
    id: 'subaru_point_gif',
    name: 'subaru_point.gif',
    emotion: 'point',
    format: 'gif',
    character: 'subaru',
    path: '/stickers/subaru/subaru_point.gif'
  },
  {
    id: 'subaru_point_png',
    name: 'subaru_point.png',
    emotion: 'point',
    format: 'png',
    character: 'subaru',
    path: '/stickers/subaru/subaru_point.png'
  },
  {
    id: 'subaru_point_webp',
    name: 'subaru_point.webp',
    emotion: 'point',
    format: 'webp',
    character: 'subaru',
    path: '/stickers/subaru/subaru_point.webp'
  },
  {
    id: 'subaru_question_png',
    name: 'subaru_question.png',
    emotion: 'question',
    format: 'png',
    character: 'subaru',
    path: '/stickers/subaru/subaru_question.png'
  },
  {
    id: 'subaru_received_png',
    name: 'subaru_received.png',
    emotion: 'received',
    format: 'png',
    character: 'subaru',
    path: '/stickers/subaru/subaru_received.png'
  },
  {
    id: 'subaru_silent_png',
    name: 'subaru_silent.png',
    emotion: 'silent',
    format: 'png',
    character: 'subaru',
    path: '/stickers/subaru/subaru_silent.png'
  },
  {
    id: 'subaru_spam_click_gif',
    name: 'subaru_spam_click.gif',
    emotion: 'spam_click',
    format: 'gif',
    character: 'subaru',
    path: '/stickers/subaru/subaru_spam_click.gif'
  },
  {
    id: 'subaru_spam_click_png',
    name: 'subaru_spam_click.png',
    emotion: 'spam_click',
    format: 'png',
    character: 'subaru',
    path: '/stickers/subaru/subaru_spam_click.png'
  },
  {
    id: 'subaru_spam_click_webp',
    name: 'subaru_spam_click.webp',
    emotion: 'spam_click',
    format: 'webp',
    character: 'subaru',
    path: '/stickers/subaru/subaru_spam_click.webp'
  },
  {
    id: 'subaru_stick_tongue_png',
    name: 'subaru_stick_tongue.png',
    emotion: 'stick_tongue',
    format: 'png',
    character: 'subaru',
    path: '/stickers/subaru/subaru_stick_tongue.png'
  },
  {
    id: 'taki_block_png',
    name: 'taki_block.png',
    emotion: 'block',
    format: 'png',
    character: 'taki',
    path: '/stickers/taki/taki_block.png'
  },
  {
    id: 'taki_glare_gif',
    name: 'taki_glare.gif',
    emotion: 'glare',
    format: 'gif',
    character: 'taki',
    path: '/stickers/taki/taki_glare.gif'
  },
  {
    id: 'taki_glare_png',
    name: 'taki_glare.png',
    emotion: 'glare',
    format: 'png',
    character: 'taki',
    path: '/stickers/taki/taki_glare.png'
  },
  {
    id: 'taki_glare_webp',
    name: 'taki_glare.webp',
    emotion: 'glare',
    format: 'webp',
    character: 'taki',
    path: '/stickers/taki/taki_glare.webp'
  },
  {
    id: 'taki_goodbye_gif',
    name: 'taki_goodbye.gif',
    emotion: 'goodbye',
    format: 'gif',
    character: 'taki',
    path: '/stickers/taki/taki_goodbye.gif'
  },
  {
    id: 'taki_goodbye_png',
    name: 'taki_goodbye.png',
    emotion: 'goodbye',
    format: 'png',
    character: 'taki',
    path: '/stickers/taki/taki_goodbye.png'
  },
  {
    id: 'taki_goodbye_webp',
    name: 'taki_goodbye.webp',
    emotion: 'goodbye',
    format: 'webp',
    character: 'taki',
    path: '/stickers/taki/taki_goodbye.webp'
  },
  {
    id: 'taki_guitar_png',
    name: 'taki_guitar.png',
    emotion: 'guitar',
    format: 'png',
    character: 'taki',
    path: '/stickers/taki/taki_guitar.png'
  },
  {
    id: 'taki_no_png',
    name: 'taki_no.png',
    emotion: 'no',
    format: 'png',
    character: 'taki',
    path: '/stickers/taki/taki_no.png'
  },
  {
    id: 'taki_please_order_png',
    name: 'taki_please_order.png',
    emotion: 'please_order',
    format: 'png',
    character: 'taki',
    path: '/stickers/taki/taki_please_order.png'
  },
  {
    id: 'taki_run_away_gif',
    name: 'taki_run_away.gif',
    emotion: 'run_away',
    format: 'gif',
    character: 'taki',
    path: '/stickers/taki/taki_run_away.gif'
  },
  {
    id: 'taki_run_away_png',
    name: 'taki_run_away.png',
    emotion: 'run_away',
    format: 'png',
    character: 'taki',
    path: '/stickers/taki/taki_run_away.png'
  },
  {
    id: 'taki_run_away_webp',
    name: 'taki_run_away.webp',
    emotion: 'run_away',
    format: 'webp',
    character: 'taki',
    path: '/stickers/taki/taki_run_away.webp'
  },
  {
    id: 'taki_suddenly_appear_png',
    name: 'taki_suddenly_appear.png',
    emotion: 'suddenly_appear',
    format: 'png',
    character: 'taki',
    path: '/stickers/taki/taki_suddenly_appear.png'
  },
  {
    id: 'taki_tsk_png',
    name: 'taki_tsk.png',
    emotion: 'tsk',
    format: 'png',
    character: 'taki',
    path: '/stickers/taki/taki_tsk.png'
  },
  {
    id: 'taki_tsundere_gif',
    name: 'taki_tsundere.gif',
    emotion: 'tsundere',
    format: 'gif',
    character: 'taki',
    path: '/stickers/taki/taki_tsundere.gif'
  },
  {
    id: 'taki_tsundere_png',
    name: 'taki_tsundere.png',
    emotion: 'tsundere',
    format: 'png',
    character: 'taki',
    path: '/stickers/taki/taki_tsundere.png'
  },
  {
    id: 'taki_tsundere_webp',
    name: 'taki_tsundere.webp',
    emotion: 'tsundere',
    format: 'webp',
    character: 'taki',
    path: '/stickers/taki/taki_tsundere.webp'
  },
  {
    id: 'taki_what_about_me_png',
    name: 'taki_what_about_me.png',
    emotion: 'what_about_me',
    format: 'png',
    character: 'taki',
    path: '/stickers/taki/taki_what_about_me.png'
  },
  {
    id: 'tomo_ah_gif',
    name: 'tomo_ah.gif',
    emotion: 'ah',
    format: 'gif',
    character: 'tomo',
    path: '/stickers/tomo/tomo_ah.gif'
  },
  {
    id: 'tomo_ah_png',
    name: 'tomo_ah.png',
    emotion: 'ah',
    format: 'png',
    character: 'tomo',
    path: '/stickers/tomo/tomo_ah.png'
  },
  {
    id: 'tomo_ah_webp',
    name: 'tomo_ah.webp',
    emotion: 'ah',
    format: 'webp',
    character: 'tomo',
    path: '/stickers/tomo/tomo_ah.webp'
  },
  {
    id: 'tomo_box_head_gif',
    name: 'tomo_box_head.gif',
    emotion: 'box_head',
    format: 'gif',
    character: 'tomo',
    path: '/stickers/tomo/tomo_box_head.gif'
  },
  {
    id: 'tomo_box_head_png',
    name: 'tomo_box_head.png',
    emotion: 'box_head',
    format: 'png',
    character: 'tomo',
    path: '/stickers/tomo/tomo_box_head.png'
  },
  {
    id: 'tomo_box_head_webp',
    name: 'tomo_box_head.webp',
    emotion: 'box_head',
    format: 'webp',
    character: 'tomo',
    path: '/stickers/tomo/tomo_box_head.webp'
  },
  {
    id: 'tomo_depressed_png',
    name: 'tomo_depressed.png',
    emotion: 'depressed',
    format: 'png',
    character: 'tomo',
    path: '/stickers/tomo/tomo_depressed.png'
  },
  {
    id: 'tomo_drinking_png',
    name: 'tomo_drinking.png',
    emotion: 'drinking',
    format: 'png',
    character: 'tomo',
    path: '/stickers/tomo/tomo_drinking.png'
  },
  {
    id: 'tomo_frozen_gif',
    name: 'tomo_frozen.gif',
    emotion: 'frozen',
    format: 'gif',
    character: 'tomo',
    path: '/stickers/tomo/tomo_frozen.gif'
  },
  {
    id: 'tomo_frozen_png',
    name: 'tomo_frozen.png',
    emotion: 'frozen',
    format: 'png',
    character: 'tomo',
    path: '/stickers/tomo/tomo_frozen.png'
  },
  {
    id: 'tomo_frozen_webp',
    name: 'tomo_frozen.webp',
    emotion: 'frozen',
    format: 'webp',
    character: 'tomo',
    path: '/stickers/tomo/tomo_frozen.webp'
  },
  {
    id: 'tomo_gnashing_teeth_png',
    name: 'tomo_gnashing_teeth.png',
    emotion: 'gnashing_teeth',
    format: 'png',
    character: 'tomo',
    path: '/stickers/tomo/tomo_gnashing_teeth.png'
  },
  {
    id: 'tomo_happy_gif',
    name: 'tomo_happy.gif',
    emotion: 'happy',
    format: 'gif',
    character: 'tomo',
    path: '/stickers/tomo/tomo_happy.gif'
  },
  {
    id: 'tomo_happy_webp',
    name: 'tomo_happy.webp',
    emotion: 'happy',
    format: 'webp',
    character: 'tomo',
    path: '/stickers/tomo/tomo_happy.webp'
  },
  {
    id: 'tomo_humph_png',
    name: 'tomo_humph.png',
    emotion: 'humph',
    format: 'png',
    character: 'tomo',
    path: '/stickers/tomo/tomo_humph.png'
  },
  {
    id: 'tomo_let_me_see_png',
    name: 'tomo_let_me_see.png',
    emotion: 'let_me_see',
    format: 'png',
    character: 'tomo',
    path: '/stickers/tomo/tomo_let_me_see.png'
  },
  {
    id: 'tomo_no_png',
    name: 'tomo_no.png',
    emotion: 'no',
    format: 'png',
    character: 'tomo',
    path: '/stickers/tomo/tomo_no.png'
  },
  {
    id: 'tomo_shocked_gif',
    name: 'tomo_shocked.gif',
    emotion: 'shocked',
    format: 'gif',
    character: 'tomo',
    path: '/stickers/tomo/tomo_shocked.gif'
  },
  {
    id: 'tomo_shocked_png',
    name: 'tomo_shocked.png',
    emotion: 'shocked',
    format: 'png',
    character: 'tomo',
    path: '/stickers/tomo/tomo_shocked.png'
  },
  {
    id: 'tomo_shocked_webp',
    name: 'tomo_shocked.webp',
    emotion: 'shocked',
    format: 'webp',
    character: 'tomo',
    path: '/stickers/tomo/tomo_shocked.webp'
  },
  {
    id: 'tomo_shy_png',
    name: 'tomo_shy.png',
    emotion: 'shy',
    format: 'png',
    character: 'tomo',
    path: '/stickers/tomo/tomo_shy.png'
  },
  {
    id: 'tomo_sweat_gif',
    name: 'tomo_sweat.gif',
    emotion: 'sweat',
    format: 'gif',
    character: 'tomo',
    path: '/stickers/tomo/tomo_sweat.gif'
  },
  {
    id: 'tomo_sweat_png',
    name: 'tomo_sweat.png',
    emotion: 'sweat',
    format: 'png',
    character: 'tomo',
    path: '/stickers/tomo/tomo_sweat.png'
  },
  {
    id: 'tomo_sweat_webp',
    name: 'tomo_sweat.webp',
    emotion: 'sweat',
    format: 'webp',
    character: 'tomo',
    path: '/stickers/tomo/tomo_sweat.webp'
  },
  {
    id: 'tomo_teary_eyed_png',
    name: 'tomo_teary_eyed.png',
    emotion: 'teary_eyed',
    format: 'png',
    character: 'tomo',
    path: '/stickers/tomo/tomo_teary_eyed.png'
  },
  {
    id: 'tomo_too_bad_png',
    name: 'tomo_too_bad.png',
    emotion: 'too_bad',
    format: 'png',
    character: 'tomo',
    path: '/stickers/tomo/tomo_too_bad.png'
  },
  {
    id: 'tomo_uh_png',
    name: 'tomo_uh.png',
    emotion: 'uh',
    format: 'png',
    character: 'tomo',
    path: '/stickers/tomo/tomo_uh.png'
  },
  {
    id: 'tomo_what_are_you_doing_gif',
    name: 'tomo_what_are_you_doing.gif',
    emotion: 'what_are_you_doing',
    format: 'gif',
    character: 'tomo',
    path: '/stickers/tomo/tomo_what_are_you_doing.gif'
  },
  {
    id: 'tomo_what_are_you_doing_png',
    name: 'tomo_what_are_you_doing.png',
    emotion: 'what_are_you_doing',
    format: 'png',
    character: 'tomo',
    path: '/stickers/tomo/tomo_what_are_you_doing.png'
  },
  {
    id: 'tomo_what_are_you_doing_webp',
    name: 'tomo_what_are_you_doing.webp',
    emotion: 'what_are_you_doing',
    format: 'webp',
    character: 'tomo',
    path: '/stickers/tomo/tomo_what_are_you_doing.webp'
  },
  {
    id: 'tomori_applaud_gif',
    name: 'tomori_applaud.gif',
    emotion: 'applaud',
    format: 'gif',
    character: 'tomori',
    path: '/stickers/tomori/tomori_applaud.gif'
  },
  {
    id: 'tomori_applaud_png',
    name: 'tomori_applaud.png',
    emotion: 'applaud',
    format: 'png',
    character: 'tomori',
    path: '/stickers/tomori/tomori_applaud.png'
  },
  {
    id: 'tomori_applaud_webp',
    name: 'tomori_applaud.webp',
    emotion: 'applaud',
    format: 'webp',
    character: 'tomori',
    path: '/stickers/tomori/tomori_applaud.webp'
  },
  {
    id: 'tomori_composing_png',
    name: 'tomori_composing.png',
    emotion: 'composing',
    format: 'png',
    character: 'tomori',
    path: '/stickers/tomori/tomori_composing.png'
  },
  {
    id: 'tomori_emo_gif',
    name: 'tomori_emo.gif',
    emotion: 'emo',
    format: 'gif',
    character: 'tomori',
    path: '/stickers/tomori/tomori_emo.gif'
  },
  {
    id: 'tomori_emo_png',
    name: 'tomori_emo.png',
    emotion: 'emo',
    format: 'png',
    character: 'tomori',
    path: '/stickers/tomori/tomori_emo.png'
  },
  {
    id: 'tomori_emo_webp',
    name: 'tomori_emo.webp',
    emotion: 'emo',
    format: 'webp',
    character: 'tomori',
    path: '/stickers/tomori/tomori_emo.webp'
  },
  {
    id: 'tomori_i_need_you_png',
    name: 'tomori_i_need_you.png',
    emotion: 'i_need_you',
    format: 'png',
    character: 'tomori',
    path: '/stickers/tomori/tomori_i_need_you.png'
  },
  {
    id: 'tomori_lost_png',
    name: 'tomori_lost.png',
    emotion: 'lost',
    format: 'png',
    character: 'tomori',
    path: '/stickers/tomori/tomori_lost.png'
  },
  {
    id: 'tomori_melancholy_png',
    name: 'tomori_melancholy.png',
    emotion: 'melancholy',
    format: 'png',
    character: 'tomori',
    path: '/stickers/tomori/tomori_melancholy.png'
  },
  {
    id: 'tomori_no_fighting_png',
    name: 'tomori_no_fighting.png',
    emotion: 'no_fighting',
    format: 'png',
    character: 'tomori',
    path: '/stickers/tomori/tomori_no_fighting.png'
  },
  {
    id: 'tomori_oops_png',
    name: 'tomori_oops.png',
    emotion: 'oops',
    format: 'png',
    character: 'tomori',
    path: '/stickers/tomori/tomori_oops.png'
  },
  {
    id: 'tomori_peek_gif',
    name: 'tomori_peek.gif',
    emotion: 'peek',
    format: 'gif',
    character: 'tomori',
    path: '/stickers/tomori/tomori_peek.gif'
  },
  {
    id: 'tomori_peek_png',
    name: 'tomori_peek.png',
    emotion: 'peek',
    format: 'png',
    character: 'tomori',
    path: '/stickers/tomori/tomori_peek.png'
  },
  {
    id: 'tomori_peek_webp',
    name: 'tomori_peek.webp',
    emotion: 'peek',
    format: 'webp',
    character: 'tomori',
    path: '/stickers/tomori/tomori_peek.webp'
  },
  {
    id: 'tomori_singing_png',
    name: 'tomori_singing.png',
    emotion: 'singing',
    format: 'png',
    character: 'tomori',
    path: '/stickers/tomori/tomori_singing.png'
  },
  {
    id: 'tomori_thank_you_all_gif',
    name: 'tomori_thank_you_all.gif',
    emotion: 'thank_you_all',
    format: 'gif',
    character: 'tomori',
    path: '/stickers/tomori/tomori_thank_you_all.gif'
  },
  {
    id: 'tomori_thank_you_all_png',
    name: 'tomori_thank_you_all.png',
    emotion: 'thank_you_all',
    format: 'png',
    character: 'tomori',
    path: '/stickers/tomori/tomori_thank_you_all.png'
  },
  {
    id: 'tomori_thank_you_all_webp',
    name: 'tomori_thank_you_all.webp',
    emotion: 'thank_you_all',
    format: 'webp',
    character: 'tomori',
    path: '/stickers/tomori/tomori_thank_you_all.webp'
  },
  {
    id: 'tomori_yes_png',
    name: 'tomori_yes.png',
    emotion: 'yes',
    format: 'png',
    character: 'tomori',
    path: '/stickers/tomori/tomori_yes.png'
  },
  {
    id: 'uika_achieved_gif',
    name: 'uika_achieved.gif',
    emotion: 'achieved',
    format: 'gif',
    character: 'uika',
    path: '/stickers/uika/uika_achieved.gif'
  },
  {
    id: 'uika_achieved_png',
    name: 'uika_achieved.png',
    emotion: 'achieved',
    format: 'png',
    character: 'uika',
    path: '/stickers/uika/uika_achieved.png'
  },
  {
    id: 'uika_achieved_webp',
    name: 'uika_achieved.webp',
    emotion: 'achieved',
    format: 'webp',
    character: 'uika',
    path: '/stickers/uika/uika_achieved.webp'
  },
  {
    id: 'uika_answer_phone_png',
    name: 'uika_answer_phone.png',
    emotion: 'answer_phone',
    format: 'png',
    character: 'uika',
    path: '/stickers/uika/uika_answer_phone.png'
  },
  {
    id: 'uika_click_tongue_gif',
    name: 'uika_click_tongue.gif',
    emotion: 'click_tongue',
    format: 'gif',
    character: 'uika',
    path: '/stickers/uika/uika_click_tongue.gif'
  },
  {
    id: 'uika_click_tongue_png',
    name: 'uika_click_tongue.png',
    emotion: 'click_tongue',
    format: 'png',
    character: 'uika',
    path: '/stickers/uika/uika_click_tongue.png'
  },
  {
    id: 'uika_click_tongue_webp',
    name: 'uika_click_tongue.webp',
    emotion: 'click_tongue',
    format: 'webp',
    character: 'uika',
    path: '/stickers/uika/uika_click_tongue.webp'
  },
  {
    id: 'uika_confiscated_png',
    name: 'uika_confiscated.png',
    emotion: 'confiscated',
    format: 'png',
    character: 'uika',
    path: '/stickers/uika/uika_confiscated.png'
  },
  {
    id: 'uika_cross_fingers_png',
    name: 'uika_cross_fingers.png',
    emotion: 'cross_fingers',
    format: 'png',
    character: 'uika',
    path: '/stickers/uika/uika_cross_fingers.png'
  },
  {
    id: 'uika_domain_expansion_gif',
    name: 'uika_domain_expansion.gif',
    emotion: 'domain_expansion',
    format: 'gif',
    character: 'uika',
    path: '/stickers/uika/uika_domain_expansion.gif'
  },
  {
    id: 'uika_domain_expansion_png',
    name: 'uika_domain_expansion.png',
    emotion: 'domain_expansion',
    format: 'png',
    character: 'uika',
    path: '/stickers/uika/uika_domain_expansion.png'
  },
  {
    id: 'uika_domain_expansion_webp',
    name: 'uika_domain_expansion.webp',
    emotion: 'domain_expansion',
    format: 'webp',
    character: 'uika',
    path: '/stickers/uika/uika_domain_expansion.webp'
  },
  {
    id: 'uika_got_wet_gif',
    name: 'uika_got_wet.gif',
    emotion: 'got_wet',
    format: 'gif',
    character: 'uika',
    path: '/stickers/uika/uika_got_wet.gif'
  },
  {
    id: 'uika_got_wet_png',
    name: 'uika_got_wet.png',
    emotion: 'got_wet',
    format: 'png',
    character: 'uika',
    path: '/stickers/uika/uika_got_wet.png'
  },
  {
    id: 'uika_got_wet_webp',
    name: 'uika_got_wet.webp',
    emotion: 'got_wet',
    format: 'webp',
    character: 'uika',
    path: '/stickers/uika/uika_got_wet.webp'
  },
  {
    id: 'uika_like_png',
    name: 'uika_like.png',
    emotion: 'like',
    format: 'png',
    character: 'uika',
    path: '/stickers/uika/uika_like.png'
  },
  {
    id: 'uika_pretty_good_png',
    name: 'uika_pretty_good.png',
    emotion: 'pretty_good',
    format: 'png',
    character: 'uika',
    path: '/stickers/uika/uika_pretty_good.png'
  },
  {
    id: 'uika_take_off_mask_gif',
    name: 'uika_take_off_mask.gif',
    emotion: 'take_off_mask',
    format: 'gif',
    character: 'uika',
    path: '/stickers/uika/uika_take_off_mask.gif'
  },
  {
    id: 'uika_take_off_mask_png',
    name: 'uika_take_off_mask.png',
    emotion: 'take_off_mask',
    format: 'png',
    character: 'uika',
    path: '/stickers/uika/uika_take_off_mask.png'
  },
  {
    id: 'uika_take_off_mask_webp',
    name: 'uika_take_off_mask.webp',
    emotion: 'take_off_mask',
    format: 'webp',
    character: 'uika',
    path: '/stickers/uika/uika_take_off_mask.webp'
  },
  {
    id: 'uika_take_off_sunglasses_gif',
    name: 'uika_take_off_sunglasses.gif',
    emotion: 'take_off_sunglasses',
    format: 'gif',
    character: 'uika',
    path: '/stickers/uika/uika_take_off_sunglasses.gif'
  },
  {
    id: 'uika_take_off_sunglasses_png',
    name: 'uika_take_off_sunglasses.png',
    emotion: 'take_off_sunglasses',
    format: 'png',
    character: 'uika',
    path: '/stickers/uika/uika_take_off_sunglasses.png'
  },
  {
    id: 'uika_take_off_sunglasses_webp',
    name: 'uika_take_off_sunglasses.webp',
    emotion: 'take_off_sunglasses',
    format: 'webp',
    character: 'uika',
    path: '/stickers/uika/uika_take_off_sunglasses.webp'
  },
  {
    id: 'uika_tears_of_joy_gif',
    name: 'uika_tears_of_joy.gif',
    emotion: 'tears_of_joy',
    format: 'gif',
    character: 'uika',
    path: '/stickers/uika/uika_tears_of_joy.gif'
  },
  {
    id: 'uika_tears_of_joy_png',
    name: 'uika_tears_of_joy.png',
    emotion: 'tears_of_joy',
    format: 'png',
    character: 'uika',
    path: '/stickers/uika/uika_tears_of_joy.png'
  },
  {
    id: 'uika_tears_of_joy_webp',
    name: 'uika_tears_of_joy.webp',
    emotion: 'tears_of_joy',
    format: 'webp',
    character: 'uika',
    path: '/stickers/uika/uika_tears_of_joy.webp'
  },
  {
    id: 'uika_wait_a_bit_more_png',
    name: 'uika_wait_a_bit_more.png',
    emotion: 'wait_a_bit_more',
    format: 'png',
    character: 'uika',
    path: '/stickers/uika/uika_wait_a_bit_more.png'
  },
  {
    id: 'umiri_buy_all_at_once_png',
    name: 'umiri_buy_all_at_once.png',
    emotion: 'buy_all_at_once',
    format: 'png',
    character: 'umiri',
    path: '/stickers/umiri/umiri_buy_all_at_once.png'
  },
  {
    id: 'umiri_cant_hold_it_gif',
    name: 'umiri_cant_hold_it.gif',
    emotion: 'cant_hold_it',
    format: 'gif',
    character: 'umiri',
    path: '/stickers/umiri/umiri_cant_hold_it.gif'
  },
  {
    id: 'umiri_cant_hold_it_png',
    name: 'umiri_cant_hold_it.png',
    emotion: 'cant_hold_it',
    format: 'png',
    character: 'umiri',
    path: '/stickers/umiri/umiri_cant_hold_it.png'
  },
  {
    id: 'umiri_cant_hold_it_webp',
    name: 'umiri_cant_hold_it.webp',
    emotion: 'cant_hold_it',
    format: 'webp',
    character: 'umiri',
    path: '/stickers/umiri/umiri_cant_hold_it.webp'
  },
  {
    id: 'umiri_chug_gif',
    name: 'umiri_chug.gif',
    emotion: 'chug',
    format: 'gif',
    character: 'umiri',
    path: '/stickers/umiri/umiri_chug.gif'
  },
  {
    id: 'umiri_chug_png',
    name: 'umiri_chug.png',
    emotion: 'chug',
    format: 'png',
    character: 'umiri',
    path: '/stickers/umiri/umiri_chug.png'
  },
  {
    id: 'umiri_chug_webp',
    name: 'umiri_chug.webp',
    emotion: 'chug',
    format: 'webp',
    character: 'umiri',
    path: '/stickers/umiri/umiri_chug.webp'
  },
  {
    id: 'umiri_cool_face_wipe_gif',
    name: 'umiri_cool_face_wipe.gif',
    emotion: 'cool_face_wipe',
    format: 'gif',
    character: 'umiri',
    path: '/stickers/umiri/umiri_cool_face_wipe.gif'
  },
  {
    id: 'umiri_cool_face_wipe_png',
    name: 'umiri_cool_face_wipe.png',
    emotion: 'cool_face_wipe',
    format: 'png',
    character: 'umiri',
    path: '/stickers/umiri/umiri_cool_face_wipe.png'
  },
  {
    id: 'umiri_cool_face_wipe_webp',
    name: 'umiri_cool_face_wipe.webp',
    emotion: 'cool_face_wipe',
    format: 'webp',
    character: 'umiri',
    path: '/stickers/umiri/umiri_cool_face_wipe.webp'
  },
  {
    id: 'umiri_eat_one_more_gif',
    name: 'umiri_eat_one_more.gif',
    emotion: 'eat_one_more',
    format: 'gif',
    character: 'umiri',
    path: '/stickers/umiri/umiri_eat_one_more.gif'
  },
  {
    id: 'umiri_eat_one_more_png',
    name: 'umiri_eat_one_more.png',
    emotion: 'eat_one_more',
    format: 'png',
    character: 'umiri',
    path: '/stickers/umiri/umiri_eat_one_more.png'
  },
  {
    id: 'umiri_eat_one_more_webp',
    name: 'umiri_eat_one_more.webp',
    emotion: 'eat_one_more',
    format: 'webp',
    character: 'umiri',
    path: '/stickers/umiri/umiri_eat_one_more.webp'
  },
  {
    id: 'umiri_good_job_gif',
    name: 'umiri_good_job.gif',
    emotion: 'good_job',
    format: 'gif',
    character: 'umiri',
    path: '/stickers/umiri/umiri_good_job.gif'
  },
  {
    id: 'umiri_good_job_png',
    name: 'umiri_good_job.png',
    emotion: 'good_job',
    format: 'png',
    character: 'umiri',
    path: '/stickers/umiri/umiri_good_job.png'
  },
  {
    id: 'umiri_good_job_webp',
    name: 'umiri_good_job.webp',
    emotion: 'good_job',
    format: 'webp',
    character: 'umiri',
    path: '/stickers/umiri/umiri_good_job.webp'
  },
  {
    id: 'umiri_ill_report_you_png',
    name: 'umiri_ill_report_you.png',
    emotion: 'ill_report_you',
    format: 'png',
    character: 'umiri',
    path: '/stickers/umiri/umiri_ill_report_you.png'
  },
  {
    id: 'umiri_open_door_png',
    name: 'umiri_open_door.png',
    emotion: 'open_door',
    format: 'png',
    character: 'umiri',
    path: '/stickers/umiri/umiri_open_door.png'
  },
  {
    id: 'umiri_really_png',
    name: 'umiri_really.png',
    emotion: 'really',
    format: 'png',
    character: 'umiri',
    path: '/stickers/umiri/umiri_really.png'
  },
  {
    id: 'umiri_respectful_png',
    name: 'umiri_respectful.png',
    emotion: 'respectful',
    format: 'png',
    character: 'umiri',
    path: '/stickers/umiri/umiri_respectful.png'
  },
  {
    id: 'umiri_shake_gif',
    name: 'umiri_shake.gif',
    emotion: 'shake',
    format: 'gif',
    character: 'umiri',
    path: '/stickers/umiri/umiri_shake.gif'
  },
  {
    id: 'umiri_shake_png',
    name: 'umiri_shake.png',
    emotion: 'shake',
    format: 'png',
    character: 'umiri',
    path: '/stickers/umiri/umiri_shake.png'
  },
  {
    id: 'umiri_shake_webp',
    name: 'umiri_shake.webp',
    emotion: 'shake',
    format: 'webp',
    character: 'umiri',
    path: '/stickers/umiri/umiri_shake.webp'
  },
  {
    id: 'umiri_sleep_png',
    name: 'umiri_sleep.png',
    emotion: 'sleep',
    format: 'png',
    character: 'umiri',
    path: '/stickers/umiri/umiri_sleep.png'
  },
  {
    id: 'umiri_so_sycophantic_png',
    name: 'umiri_so_sycophantic.png',
    emotion: 'so_sycophantic',
    format: 'png',
    character: 'umiri',
    path: '/stickers/umiri/umiri_so_sycophantic.png'
  },
  {
    id: 'umiri_want_to_trust_gif',
    name: 'umiri_want_to_trust.gif',
    emotion: 'want_to_trust',
    format: 'gif',
    character: 'umiri',
    path: '/stickers/umiri/umiri_want_to_trust.gif'
  },
  {
    id: 'umiri_want_to_trust_png',
    name: 'umiri_want_to_trust.png',
    emotion: 'want_to_trust',
    format: 'png',
    character: 'umiri',
    path: '/stickers/umiri/umiri_want_to_trust.png'
  },
  {
    id: 'umiri_want_to_trust_webp',
    name: 'umiri_want_to_trust.webp',
    emotion: 'want_to_trust',
    format: 'webp',
    character: 'umiri',
    path: '/stickers/umiri/umiri_want_to_trust.webp'
  },
  {
    id: 'umiri_yo_png',
    name: 'umiri_yo.png',
    emotion: 'yo',
    format: 'png',
    character: 'umiri',
    path: '/stickers/umiri/umiri_yo.png'
  },
]

export const STICKERS_COUNT = stickers.length
